image: debian:stable

before_script:
  - apt-get update -yq && apt-get install -yq gcc g++ gfortran make python3 python3-numpy
  - gfortran --version

cache:
  paths:
    - afivo/external_libraries

build:
  stage: build
  script:
    - make -j

run_tests:
  stage: test
  script:
    - ./run_test.sh
