#!/bin/bash

#SBATCH --nodes=1	     # number of nodes on which to run
#SBATCH --ntasks=8	     # number of tasks to run
#SBATCH --cpus-per-task=16    # number of cpus required per task
#SBATCH --partition=rome	     # partition requested
#SBATCH --mem=128G             # memory requested
#SBATCH --time=5-00:00:00	     # wall-clock time limit


module load 2022
module load GCC/11.3.0

export OMP_NUM_THREADS=32
export GFORTRAN_UNBUFFERED_PRECONNECTED=y


cd /home/baohongg/humid_air/afivo-streamer/programs/humid_2d/

./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=71 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0071_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=71 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0071_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=71 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0071_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=71 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0071_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=72 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0072_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=72 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0072_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=72 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0072_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=72 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0072_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=73 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0073_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=73 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0073_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=73 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0073_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=73 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0073_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=74 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0074_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=74 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0074_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=74 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0074_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=74 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0074_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=75 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0075_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=75 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0075_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=75 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0075_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=75 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0075_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=76 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0076_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=76 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0076_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=76 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0076_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=76 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0076_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=77 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0077_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=77 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0077_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=77 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0077_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=77 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0077_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=78 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0078_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=78 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0078_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=78 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0078_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=78 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0078_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=79 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0079_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=79 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0079_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=79 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0079_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=79 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0079_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=80 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0080_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=80 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0080_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=80 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0080_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=80 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0080_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=81 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0081_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=81 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0081_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=81 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0081_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=81 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0081_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=82 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0082_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=82 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0082_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=82 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0082_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=82 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0082_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=83 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0083_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=83 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0083_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=83 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0083_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=83 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0083_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=84 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0084_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=84 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0084_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=84 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0084_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=84 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0084_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=85 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0085_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=85 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0085_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=85 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0085_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=85 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0085_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=86 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0086_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=86 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0086_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=86 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0086_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=86 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0086_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=87 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0087_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=87 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0087_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=87 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0087_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=87 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0087_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=88 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0088_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=88 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0088_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=88 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0088_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=88 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0088_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=89 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0089_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=89 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0089_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=89 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0089_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=89 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0089_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=90 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0090_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=90 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0090_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=90 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0090_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=90 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0090_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=91 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0091_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=91 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0091_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=91 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0091_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=91 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0091_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=92 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0092_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=92 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0092_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=92 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0092_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=92 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0092_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=93 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0093_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=93 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0093_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=93 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0093_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=93 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0093_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=94 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0094_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=94 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0094_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=94 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0094_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=94 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0094_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=95 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0095_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=95 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0095_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=95 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0095_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=95 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0095_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=96 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0096_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=96 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0096_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=96 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0096_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=96 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0096_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=97 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0097_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=97 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0097_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=97 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0097_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=97 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0097_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=98 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0098_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=98 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0098_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=98 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0098_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=98 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0098_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=99 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0099_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=99 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0099_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=99 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0099_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=99 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0099_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=100 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0100_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=100 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0100_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=100 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0100_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=100 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0100_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=101 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0101_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=101 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0101_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=101 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0101_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=101 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0101_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=102 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0102_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=102 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0102_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=102 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0102_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=102 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0102_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=103 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0103_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=103 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0103_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=103 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0103_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=103 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0103_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=104 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0104_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=104 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0104_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=104 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0104_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=104 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0104_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=105 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0105_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=105 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0105_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=105 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0105_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=105 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0105_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=106 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0106_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=106 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0106_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=106 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0106_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=106 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0106_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=107 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0107_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=107 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0107_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=107 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0107_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=107 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0107_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=108 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0108_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=108 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0108_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=108 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0108_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=108 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0108_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=109 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0109_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=109 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0109_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=109 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0109_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=109 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0109_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=110 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0110_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=110 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0110_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=110 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0110_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=110 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0110_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=111 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0111_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=111 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0111_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=111 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0111_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=111 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0111_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=112 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0112_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=112 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0112_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=112 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0112_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=112 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0112_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=113 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0113_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=113 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0113_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=113 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0113_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=113 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0113_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=114 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0114_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=114 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0114_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=114 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0114_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=114 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0114_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=115 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0115_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=115 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0115_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=115 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0115_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=115 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0115_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=116 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0116_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=116 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0116_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=116 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0116_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=116 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0116_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=117 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0117_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=117 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0117_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=117 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0117_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=117 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0117_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=118 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0118_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=118 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0118_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=118 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0118_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=118 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0118_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=119 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0119_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=119 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0119_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=119 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0119_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=119 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0119_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=120 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0120_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=120 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0120_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=120 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0120_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=120 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0120_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=121 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0121_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=121 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0121_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=121 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0121_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=121 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0121_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=122 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0122_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=122 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0122_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=122 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0122_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=122 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0122_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=123 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0123_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=123 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0123_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=123 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0123_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=123 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0123_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=124 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0124_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=124 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0124_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=124 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0124_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=124 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0124_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=125 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0125_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=125 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0125_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=125 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0125_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=125 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0125_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=126 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0126_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=126 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0126_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=126 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0126_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=126 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0126_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=127 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0127_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=127 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0127_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=127 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0127_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=127 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0127_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=128 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0128_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=128 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0128_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=128 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0128_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=128 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0128_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=129 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0129_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=129 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0129_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=129 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0129_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=129 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0129_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=130 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0130_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=130 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0130_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=130 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0130_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=130 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0130_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=131 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0131_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=131 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0131_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=131 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0131_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=131 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0131_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=132 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0132_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=132 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0132_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=132 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0132_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=132 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0132_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=133 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0133_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=133 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0133_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=133 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0133_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=133 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0133_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=134 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0134_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=134 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0134_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=134 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0134_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=134 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0134_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=135 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0135_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=135 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0135_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=135 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0135_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=135 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0135_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=136 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0136_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=136 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0136_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=136 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0136_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=136 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0136_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=137 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0137_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=137 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0137_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=137 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0137_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=137 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0137_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=138 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0138_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=138 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0138_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=138 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0138_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=138 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0138_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=139 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0139_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=139 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0139_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=139 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0139_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=139 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0139_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=140 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0140_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=140 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0140_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=140 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0140_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=140 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0140_fac0.75 &

wait

