#!/bin/bash

#SBATCH --nodes=1	     # number of nodes on which to run
#SBATCH --ntasks=8	     # number of tasks to run
#SBATCH --cpus-per-task=16    # number of cpus required per task
#SBATCH --partition=rome	     # partition requested
#SBATCH --mem=128G             # memory requested
#SBATCH --time=5-00:00:00	     # wall-clock time limit


module load 2022
module load GCC/11.3.0

export OMP_NUM_THREADS=32
export GFORTRAN_UNBUFFERED_PRECONNECTED=y


cd /home/baohongg/humid_air/afivo-streamer/programs/humid_2d/

./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=211 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0211_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=211 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0211_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=211 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0211_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=211 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0211_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=212 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0212_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=212 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0212_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=212 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0212_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=212 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0212_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=213 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0213_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=213 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0213_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=213 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0213_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=213 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0213_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=214 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0214_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=214 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0214_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=214 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0214_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=214 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0214_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=215 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0215_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=215 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0215_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=215 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0215_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=215 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0215_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=216 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0216_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=216 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0216_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=216 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0216_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=216 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0216_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=217 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0217_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=217 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0217_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=217 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0217_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=217 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0217_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=218 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0218_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=218 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0218_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=218 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0218_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=218 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0218_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=219 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0219_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=219 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0219_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=219 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0219_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=219 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0219_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=220 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0220_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=220 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0220_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=220 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0220_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=220 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0220_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=221 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0221_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=221 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0221_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=221 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0221_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=221 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0221_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=222 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0222_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=222 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0222_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=222 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0222_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=222 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0222_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=223 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0223_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=223 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0223_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=223 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0223_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=223 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0223_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=224 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0224_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=224 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0224_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=224 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0224_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=224 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0224_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=225 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0225_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=225 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0225_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=225 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0225_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=225 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0225_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=226 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0226_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=226 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0226_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=226 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0226_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=226 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0226_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=227 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0227_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=227 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0227_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=227 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0227_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=227 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0227_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=228 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0228_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=228 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0228_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=228 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0228_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=228 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0228_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=229 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0229_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=229 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0229_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=229 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0229_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=229 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0229_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=230 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0230_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=230 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0230_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=230 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0230_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=230 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0230_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=231 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0231_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=231 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0231_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=231 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0231_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=231 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0231_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=232 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0232_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=232 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0232_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=232 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0232_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=232 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0232_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=233 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0233_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=233 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0233_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=233 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0233_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=233 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0233_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=234 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0234_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=234 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0234_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=234 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0234_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=234 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0234_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=235 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0235_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=235 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0235_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=235 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0235_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=235 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0235_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=236 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0236_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=236 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0236_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=236 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0236_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=236 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0236_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=237 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0237_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=237 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0237_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=237 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0237_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=237 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0237_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=238 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0238_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=238 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0238_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=238 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0238_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=238 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0238_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=239 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0239_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=239 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0239_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=239 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0239_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=239 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0239_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=240 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0240_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=240 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0240_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=240 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0240_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=240 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0240_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=241 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0241_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=241 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0241_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=241 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0241_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=241 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0241_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=242 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0242_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=242 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0242_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=242 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0242_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=242 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0242_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=243 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0243_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=243 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0243_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=243 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0243_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=243 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0243_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=244 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0244_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=244 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0244_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=244 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0244_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=244 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0244_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=245 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0245_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=245 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0245_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=245 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0245_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=245 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0245_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=246 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0246_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=246 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0246_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=246 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0246_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=246 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0246_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=247 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0247_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=247 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0247_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=247 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0247_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=247 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0247_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=248 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0248_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=248 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0248_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=248 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0248_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=248 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0248_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=249 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0249_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=249 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0249_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=249 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0249_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=249 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0249_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=250 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0250_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=250 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0250_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=250 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0250_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=250 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0250_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=251 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0251_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=251 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0251_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=251 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0251_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=251 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0251_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=252 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0252_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=252 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0252_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=252 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0252_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=252 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0252_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=253 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0253_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=253 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0253_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=253 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0253_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=253 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0253_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=254 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0254_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=254 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0254_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=254 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0254_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=254 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0254_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=255 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0255_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=255 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0255_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=255 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0255_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=255 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0255_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=256 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0256_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=256 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0256_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=256 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0256_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=256 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0256_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=257 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0257_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=257 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0257_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=257 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0257_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=257 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0257_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=258 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0258_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=258 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0258_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=258 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0258_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=258 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0258_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=259 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0259_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=259 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0259_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=259 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0259_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=259 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0259_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=260 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0260_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=260 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0260_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=260 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0260_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=260 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0260_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=261 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0261_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=261 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0261_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=261 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0261_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=261 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0261_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=262 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0262_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=262 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0262_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=262 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0262_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=262 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0262_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=263 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0263_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=263 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0263_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=263 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0263_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=263 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0263_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=264 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0264_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=264 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0264_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=264 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0264_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=264 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0264_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=265 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0265_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=265 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0265_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=265 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0265_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=265 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0265_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=266 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0266_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=266 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0266_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=266 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0266_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=266 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0266_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=267 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0267_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=267 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0267_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=267 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0267_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=267 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0267_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=268 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0268_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=268 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0268_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=268 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0268_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=268 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0268_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=269 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0269_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=269 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0269_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=269 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0269_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=269 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0269_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=270 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0270_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=270 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0270_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=270 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0270_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=270 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0270_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=271 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0271_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=271 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0271_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=271 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0271_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=271 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0271_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=272 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0272_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=272 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0272_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=272 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0272_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=272 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0272_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=273 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0273_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=273 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0273_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=273 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0273_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=273 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0273_fac0.75 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=274 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0274_fac0.0 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=274 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0274_fac0.25 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=274 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0274_fac0.5 &
./streamer d200mm_sensitivity_baohong_0.00H2O.cfg -input_data%modified_reaction_ix=274 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/baohong_chemistry_ix0274_fac0.75 &

wait

