#!/bin/bash

#SBATCH --nodes=1	     # number of nodes on which to run
#SBATCH --ntasks=8	     # number of tasks to run
#SBATCH --cpus-per-task=16    # number of cpus required per task
#SBATCH --partition=rome	     # partition requested
#SBATCH --mem=128G             # memory requested
#SBATCH --time=5-00:00:00	     # wall-clock time limit


module load 2022
module load GCC/11.3.0

export OMP_NUM_THREADS=32
export GFORTRAN_UNBUFFERED_PRECONNECTED=y


cd /home/baohongg/humid_air/afivo-streamer/programs/humid_2d/

./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=146 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0146_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=146 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0146_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=146 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0146_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=146 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0146_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=147 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0147_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=147 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0147_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=147 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0147_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=147 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0147_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=148 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0148_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=148 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0148_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=148 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0148_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=148 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0148_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=149 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0149_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=149 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0149_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=149 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0149_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=149 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0149_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=150 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0150_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=150 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0150_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=150 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0150_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=150 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0150_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=151 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0151_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=151 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0151_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=151 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0151_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=151 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0151_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=152 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0152_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=152 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0152_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=152 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0152_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=152 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0152_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=153 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0153_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=153 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0153_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=153 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0153_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=153 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0153_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=154 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0154_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=154 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0154_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=154 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0154_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=154 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0154_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=155 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0155_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=155 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0155_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=155 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0155_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=155 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0155_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=156 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0156_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=156 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0156_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=156 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0156_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=156 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0156_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=157 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0157_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=157 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0157_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=157 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0157_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=157 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0157_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=158 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0158_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=158 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0158_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=158 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0158_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=158 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0158_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=159 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0159_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=159 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0159_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=159 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0159_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=159 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0159_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=160 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0160_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=160 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0160_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=160 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0160_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=160 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0160_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=161 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0161_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=161 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0161_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=161 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0161_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=161 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0161_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=162 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0162_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=162 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0162_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=162 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0162_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=162 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0162_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=163 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0163_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=163 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0163_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=163 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0163_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=163 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0163_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=164 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0164_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=164 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0164_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=164 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0164_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=164 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0164_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=165 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0165_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=165 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0165_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=165 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0165_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=165 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0165_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=166 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0166_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=166 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0166_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=166 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0166_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=166 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0166_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=167 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0167_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=167 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0167_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=167 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0167_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=167 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0167_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=168 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0168_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=168 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0168_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=168 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0168_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=168 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0168_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=169 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0169_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=169 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0169_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=169 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0169_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=169 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0169_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=170 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0170_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=170 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0170_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=170 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0170_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=170 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0170_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=171 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0171_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=171 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0171_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=171 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0171_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=171 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0171_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=172 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0172_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=172 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0172_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=172 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0172_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=172 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0172_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=173 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0173_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=173 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0173_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=173 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0173_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=173 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0173_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=174 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0174_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=174 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0174_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=174 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0174_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=174 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0174_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=175 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0175_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=175 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0175_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=175 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0175_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=175 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0175_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=176 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0176_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=176 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0176_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=176 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0176_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=176 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0176_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=177 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0177_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=177 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0177_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=177 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0177_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=177 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0177_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=178 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0178_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=178 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0178_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=178 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0178_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=178 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0178_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=179 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0179_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=179 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0179_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=179 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0179_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=179 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0179_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=180 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0180_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=180 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0180_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=180 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0180_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=180 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0180_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=181 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0181_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=181 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0181_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=181 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0181_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=181 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0181_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=182 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0182_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=182 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0182_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=182 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0182_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=182 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0182_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=183 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0183_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=183 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0183_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=183 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0183_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=183 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0183_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=184 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0184_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=184 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0184_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=184 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0184_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=184 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0184_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=185 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0185_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=185 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0185_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=185 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0185_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=185 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0185_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=186 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0186_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=186 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0186_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=186 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0186_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=186 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0186_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=187 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0187_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=187 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0187_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=187 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0187_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=187 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0187_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=188 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0188_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=188 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0188_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=188 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0188_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=188 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0188_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=189 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0189_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=189 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0189_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=189 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0189_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=189 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0189_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=190 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0190_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=190 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0190_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=190 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0190_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=190 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0190_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=191 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0191_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=191 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0191_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=191 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0191_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=191 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0191_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=192 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0192_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=192 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0192_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=192 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0192_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=192 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0192_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=193 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0193_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=193 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0193_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=193 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0193_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=193 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0193_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=194 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0194_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=194 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0194_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=194 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0194_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=194 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0194_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=195 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0195_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=195 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0195_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=195 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0195_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=195 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0195_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=196 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0196_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=196 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0196_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=196 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0196_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=196 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0196_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=197 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0197_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=197 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0197_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=197 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0197_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=197 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0197_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=198 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0198_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=198 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0198_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=198 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0198_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=198 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0198_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=199 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0199_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=199 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0199_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=199 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0199_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=199 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0199_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=200 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0200_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=200 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0200_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=200 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0200_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=200 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0200_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=201 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0201_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=201 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0201_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=201 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0201_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=201 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0201_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=202 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0202_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=202 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0202_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=202 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0202_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=202 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0202_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=203 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0203_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=203 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0203_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=203 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0203_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=203 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0203_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=204 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0204_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=204 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0204_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=204 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0204_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=204 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0204_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=205 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0205_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=205 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0205_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=205 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0205_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=205 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0205_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=206 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0206_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=206 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0206_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=206 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0206_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=206 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0206_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=207 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0207_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=207 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0207_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=207 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0207_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=207 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0207_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=208 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0208_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=208 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0208_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=208 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0208_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=208 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0208_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=209 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0209_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=209 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0209_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=209 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0209_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=209 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0209_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=210 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0210_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=210 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0210_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=210 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0210_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=210 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0210_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=211 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0211_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=211 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0211_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=211 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0211_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=211 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0211_fac0.75 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=212 -input_data%modified_rate_factors=0.0 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0212_fac0.0 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=212 -input_data%modified_rate_factors=0.25 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0212_fac0.25 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=212 -input_data%modified_rate_factors=0.5 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0212_fac0.5 &
./streamer d200mm_sensitivity_komuro_0.03H2O.cfg -input_data%modified_reaction_ix=212 -input_data%modified_rate_factors=0.75 -output%name=/scratch-shared/baohongg/komuro_chemistry_ix0212_fac0.75 &

wait

