#!/bin/bash

cd ../

# air, background density=1e11, electrode length=1e-3, electode radius=0.1e-3, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt


#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="1024 1024" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.1e-3 -field_amplitude=2.0863592155e6 -output%name=/export/scratch2/md/baohong/negative_125mm_electrode_size/neg_EL1mm_ER0.1mm_2.0863592155e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="1024 1024" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.1e-3 -field_amplitude=2.0863592161e6 -output%name=/export/scratch2/md/baohong/negative_125mm_electrode_size/neg_EL1mm_ER0.1mm_2.0863592161e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="1024 1024" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.1e-3 -field_amplitude=2.0863592157e6 -output%name=/export/scratch2/md/baohong/negative_125mm_electrode_size/neg_EL1mm_ER0.1mm_2.0863592157e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="1024 1024" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.1e-3 -field_amplitude=2.0863592159e6 -output%name=/export/scratch2/md/baohong/negative_125mm_electrode_size/neg_EL1mm_ER0.1mm_2.0863592159e6


#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.76e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.76e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.755e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.755e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.75e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.75e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.745e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.745e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.74e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.74e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.735e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.735e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.73e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.73e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.725e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.725e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.72e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.72e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.715e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.715e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.71e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.71e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.70e6 -output%name=/export/scratch2/md/baohong/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.70e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=1.05e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_1.05e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=1.04e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_1.04e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=1.03e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_1.03e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=1.02e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_1.02e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=1.01e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_1.01e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=1.00e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_1.00e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=0.98e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_0.98e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=0.96e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_0.96e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=0.94e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_0.94e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=0.92e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_0.92e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=0.90e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_0.90e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=0.85e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_0.85e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%initial_field=2.0e6 -field_decay%min_field=0.80e6 -field_decay%decay_distance=5e-3 -field_decay%decay_start_z=115.1e-3 -output%name=/export/scratch2/md/baohong/negative_artificially_decay_2mm/neg_EL2mm_2.0e6_0.80e6_5e-3_115.1e-3



#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1684e6 -output%name=/export/scratch2/md/baohong/initial_seed/neg_EL9mm_ER0.9mm_1.1684e6_seed

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1684e6 -output%name=/export/scratch2/md/baohong/initial_seed/neg_EL9mm_ER0.9mm_1.1684e6_bg

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.155e6 -output%name=/export/scratch2/md/baohong/initial_seed/neg_EL9mm_ER0.9mm_1.155e6_seeds

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.155e6 -output%name=/export/scratch2/md/baohong/initial_seed/neg_EL9mm_ER0.9mm_1.155e6_bg


#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1684e6 -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points.txt -output%name=/export/scratch2/md/baohong/input_data/neg_EL9mm_ER0.9mm_1.1684e6_bg

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1684e6 -input_data%file=../../transport_data/air_chemistry_phelps_bminus.txt -output%name=/export/scratch2/md/baohong/input_data/neg_EL9mm_ER0.9mm_1.1684e6_hani

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1684e6 -input_data%file=../../transport_data/air_chemistry_v1.txt -output%name=/export/scratch2/md/baohong/input_data/neg_EL9mm_ER0.9mm_1.1684e6_v1

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1684e6 -input_data%file=../../transport_data/xiaoran_8N2_2O2.txt -output%name=/export/scratch2/md/baohong/input_data/neg_EL9mm_ER0.9mm_1.1684e6_xr

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1684e6 -input_data%file=../../transport_data/air_chemistry_phelps_bminus.txt -output%name=/export/scratch2/md/baohong/input_data/neg_EL9mm_ER0.9mm_1.1684e6_hani_add_ion_recombinations

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1684e6 -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_electron_e_recombination.txt -output%name=/export/scratch2/md/baohong/input_data/neg_EL9mm_ER0.9mm_1.1684e6_bg_e_recombinations

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1684e6 -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_electron_ions_recombination.txt -output%name=/export/scratch2/md/baohong/input_data/neg_EL9mm_ER0.9mm_1.1684e6_bg_all_recombinations




#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.4e-3 -field_amplitude=0.880e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL24mm_ER2.4mm_0.880e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.4e-3 -field_amplitude=0.885e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL24mm_ER2.4mm_0.885e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.4e-3 -field_amplitude=0.890e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL24mm_ER2.4mm_0.890e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.4e-3 -field_amplitude=0.900e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL24mm_ER2.4mm_0.900e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.4e-3 -field_amplitude=0.905e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL24mm_ER2.4mm_0.905e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.4e-3 -field_amplitude=0.910e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL24mm_ER2.4mm_0.910e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.4e-3 -field_amplitude=0.915e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL24mm_ER2.4mm_0.915e6


#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.892" -field_rod_radius=2.7e-3 -field_amplitude=0.850e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL27mm_ER2.7mm_0.850e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.892" -field_rod_radius=2.7e-3 -field_amplitude=0.855e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL27mm_ER2.7mm_0.855e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.892" -field_rod_radius=2.7e-3 -field_amplitude=0.860e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL27mm_ER2.7mm_0.860e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.892" -field_rod_radius=2.7e-3 -field_amplitude=0.870e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL27mm_ER2.7mm_0.870e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.892" -field_rod_radius=2.7e-3 -field_amplitude=0.875e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL27mm_ER2.7mm_0.875e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.892" -field_rod_radius=2.7e-3 -field_amplitude=0.880e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL27mm_ER2.7mm_0.880e6



#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=3.0e-3 -field_amplitude=0.825e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL30mm_ER3.0mm_0.825e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=3.0e-3 -field_amplitude=0.830e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL30mm_ER3.0mm_0.830e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=3.0e-3 -field_amplitude=0.835e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL30mm_ER3.0mm_0.835e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=3.0e-3 -field_amplitude=0.860e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL30mm_ER3.0mm_0.860e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=3.0e-3 -field_amplitude=0.865e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL30mm_ER3.0mm_0.865e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=3.0e-3 -field_amplitude=0.870e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL30mm_ER3.0mm_0.870e6



#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.868" -field_rod_radius=3.3e-3 -field_amplitude=0.800e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL33mm_ER3.3mm_0.800e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.868" -field_rod_radius=3.3e-3 -field_amplitude=0.805e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL33mm_ER3.3mm_0.805e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.868" -field_rod_radius=3.3e-3 -field_amplitude=0.810e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL33mm_ER3.3mm_0.810e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.868" -field_rod_radius=3.3e-3 -field_amplitude=0.825e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL33mm_ER3.3mm_0.825e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.868" -field_rod_radius=3.3e-3 -field_amplitude=0.830e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL33mm_ER3.3mm_0.830e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.868" -field_rod_radius=3.3e-3 -field_amplitude=0.835e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL33mm_ER3.3mm_0.835e6



#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.856" -field_rod_radius=3.6e-3 -field_amplitude=0.780e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL36mm_ER3.6mm_0.780e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.856" -field_rod_radius=3.6e-3 -field_amplitude=0.785e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL36mm_ER3.6mm_0.785e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.856" -field_rod_radius=3.6e-3 -field_amplitude=0.790e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL36mm_ER3.6mm_0.790e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.856" -field_rod_radius=3.6e-3 -field_amplitude=0.800e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL36mm_ER3.6mm_0.800e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.856" -field_rod_radius=3.6e-3 -field_amplitude=0.805e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL36mm_ER3.6mm_0.805e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.856" -field_rod_radius=3.6e-3 -field_amplitude=0.810e6 -output%name=/export/scratch2/md/baohong/domain_250mm/neg_EL36mm_ER3.6mm_0.810e6



#./streamer air_negative_160mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.85" -field_rod_radius=2.4e-3 -field_amplitude=0.85e6 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/electrode_24mm/dm160mm_neg_EL24mm_ER2.4mm_0.85e6

#./streamer air_negative_200mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=2.4e-3 -field_amplitude=0.85e6 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/electrode_24mm/dm200mm_neg_EL24mm_ER2.4mm_0.85e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.4e-3 -field_amplitude=0.88e6 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/electrode_24mm/dm250mm_neg_EL24mm_ER2.4mm_0.88e6





#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.182e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.182e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.181e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.181e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.179e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.179e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.178e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.178e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.164e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.164e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.163e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.163e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.162e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.162e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.159e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.159e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.158e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.158e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.157e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.157e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.156e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.156e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.053e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.053e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.052e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.052e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=0.982e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_0.982e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=0.981e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_0.981e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=0.980e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_0.980e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.115e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.115e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.154e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.154e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.160e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.160e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.161e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.161e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.183e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.183e6






#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=0.98212528e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.0666e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=0.98221736e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.0667e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=0.98230944e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.0668e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.05210608e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.1426e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.05219816e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.1427e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.08774104e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.1813e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.08783312e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.1814e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.11545712e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2114e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1155492e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2115e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.11564128e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2116e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1298216e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2270e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.12991368e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2271e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.13939792e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2374e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.13949e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2375e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.13958208e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2376e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.14667224e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2453e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.14676432e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2454e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1468564e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2455e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.15173664e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2508e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.15182872e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2509e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1519208e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2510e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.15523568e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2546e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.15532776e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2547e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.160208e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2600e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.16030008e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2601e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.18212304e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2838e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.18221512e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2839e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -output%dt=5e-10 -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1823072e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2840e6



#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=0.98258568e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.0671e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=0.98267776e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.0672e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.16149712e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2614e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1615892e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2615e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.16168128e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2616e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.16177336e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2617e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.17972896e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2812e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.17982104e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2813e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.17991312e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2814e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1800052e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2815e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.18009728e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2816e6



#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=0.98240152e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.0669e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.15569608e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2551e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.15578816e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2552e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.15588024e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2553e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.15597232e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2554e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1560644e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2555e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.16122088e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2611e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.16131296e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2612e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.16140504e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2613e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.17945272e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2809e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1795448e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2810e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.17963688e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_9mm/neg_EL9mm_ER0.9mm_1.2811e6



#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -field_amplitude=1.11172248e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_7mm/neg_EL7mm_ER0.7mm_1.1847e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -field_amplitude=1.16896488e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_7mm/neg_EL7mm_ER0.7mm_1.2457e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -field_amplitude=1.22423664e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_7mm/neg_EL7mm_ER0.7mm_1.3046e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -field_amplitude=1.24262928e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_7mm/neg_EL7mm_ER0.7mm_1.3242e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -field_amplitude=1.24563216e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_7mm/neg_EL7mm_ER0.7mm_1.3274e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=1.02e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_1.02e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=1.00e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_1.00e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.99e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.99e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.98e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.98e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.97e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.97e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.96e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.96e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.95e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.95e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.94e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.94e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.92e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.92e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.90e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.90e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.88e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.88e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.86e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.86e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.84e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.84e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.82e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.82e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.80e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.80e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.75e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.75e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.70e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.70e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.65e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.60e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.60e6




#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -end_streamer_length=100e-3 -field_amplitude=1.06585648e6 -output%name=/export/scratch2/md/baohong/negative_decay_12mm/neg_EL12mm_ER1.2mm_1.1917e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -end_streamer_length=100e-3 -field_amplitude=1.06594592e6 -output%name=/export/scratch2/md/baohong/negative_decay_12mm/neg_EL12mm_ER1.2mm_1.1918e6


#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -field_amplitude=1.15615648e6 -output%name=/export/scratch2/md/baohong/negative_decay_12mm/neg_EL9mm_ER0.9mm_1.2556e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -field_amplitude=1.16195752e6 -output%name=/export/scratch2/md/baohong/negative_decay_12mm/neg_EL9mm_ER0.9mm_1.2619e6





#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=250e-9 -field_amplitude=1.574671432e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL3mm_ER0.3mm_1.61737e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.575099816e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL3mm_ER0.3mm_1.61781e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.575109552e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL3mm_ER0.3mm_1.61782e6



#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -end_streamer_length=105e-3 -end_time=250e-9 -field_amplitude=1.455362208e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL4mm_ER0.4mm_1.50846e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -end_streamer_length=105e-3 -end_time=250e-9 -field_amplitude=1.455371856e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL4mm_ER0.4mm_1.50847e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -end_streamer_length=105e-3 -end_time=250e-9 -field_amplitude=1.455381504e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL4mm_ER0.4mm_1.50848e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -end_streamer_length=105e-3 -end_time=250e-9 -field_amplitude=1.455912144e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL4mm_ER0.4mm_1.50903e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -end_streamer_length=105e-3 -end_time=250e-9 -field_amplitude=1.455921792e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL4mm_ER0.4mm_1.50904e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -end_streamer_length=105e-3 -end_time=250e-9 -field_amplitude=1.45593144e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL4mm_ER0.4mm_1.50905e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.457262864e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL4mm_ER0.4mm_1.51043e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.457272512e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL4mm_ER0.4mm_1.51044e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.45728216e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL4mm_ER0.4mm_1.51045e6



#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.96" -field_rod_radius=0.5e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.3682272e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL5mm_ER0.5mm_1.43120e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.96" -field_rod_radius=0.5e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.37132464e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL5mm_ER0.5mm_1.43444e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.96" -field_rod_radius=0.5e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.3713342e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL5mm_ER0.5mm_1.43445e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.96" -field_rod_radius=0.5e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.37134376e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL5mm_ER0.5mm_1.43446e6




#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.242835728e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL7mm_ER0.7mm_1.32442e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.242845112e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL7mm_ER0.7mm_1.32443e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.242854496e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL7mm_ER0.7mm_1.32444e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.245782304e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL7mm_ER0.7mm_1.32756e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.245791688e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL7mm_ER0.7mm_1.32757e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.245801072e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL7mm_ER0.7mm_1.32758e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.255560432e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL7mm_ER0.7mm_1.33798e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.255569816e6 -output%name=/export/scratch2/md/baohong/negative_decay/neg_EL7mm_ER0.7mm_1.33799e6




./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -dt_min=1e-15 -field_amplitude=-1.27712e6 -output%name=/export/scratch2/md/baohong/electro2mm_constant/pos_EL2mm_ER0.2mm_1.3e6

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -dt_min=1e-15 -field_amplitude=-1.37536e6 -output%name=/export/scratch2/md/baohong/electro2mm_constant/pos_EL2mm_ER0.2mm_1.4e6
