#!/bin/bash

cd ../

# air, background density=1e11, electrode length=12e-3, electode radius=1.2e-3, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt


#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=1.10e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_1.10e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=1.09e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_1.09e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=1.049e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_1.049e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=1.048e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_1.048e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=1.042e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_1.042e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=1.041e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_1.041e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=1.032e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_1.032e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=1.031e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_1.031e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=1.019e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_1.019e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=1.018e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_1.018e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=1.017e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_1.017e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.999e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.999e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.998e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.998e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.997e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.997e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.975e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.975e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.970e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.970e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.965e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.965e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.926e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.926e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.924e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.924e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.922e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.922e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.836e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.836e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.834e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.834e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.832e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.832e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -field_amplitude=0.75e6 -output%name+=negative_decay_12mm/neg_EL12mm_ER1.2mm_0.75e6




#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.58e6 -output%name+=negative_decay_3mm/neg_EL3mm_ER0.3mm_1.58e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.57e6 -output%name+=negative_decay_3mm/neg_EL3mm_ER0.3mm_1.57e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.565e6 -output%name+=negative_decay_3mm/neg_EL3mm_ER0.3mm_1.565e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.56e6 -output%name+=negative_decay_3mm/neg_EL3mm_ER0.3mm_1.56e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.555e6 -output%name+=negative_decay_3mm/neg_EL3mm_ER0.3mm_1.555e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.55e6 -output%name+=negative_decay_3mm/neg_EL3mm_ER0.3mm_1.55e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.54e6 -output%name+=negative_decay_3mm/neg_EL3mm_ER0.3mm_1.54e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.52e6 -output%name+=negative_decay_3mm/neg_EL3mm_ER0.3mm_1.52e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.50e6 -output%name+=negative_decay_3mm/neg_EL3mm_ER0.3mm_1.50e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.45e6 -output%name+=negative_decay_3mm/neg_EL3mm_ER0.3mm_1.45e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.40e6 -output%name+=negative_decay_3mm/neg_EL3mm_ER0.3mm_1.40e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=1.02e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_1.02e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=1.00e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_1.00e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.99e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.99e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.98e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.98e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.97e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.97e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.96e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.96e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.95e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.95e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.94e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.94e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.92e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.92e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.90e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.90e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.88e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.88e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.86e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.86e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.84e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.84e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.82e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.82e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.80e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.80e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.75e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.75e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.70e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.70e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.65e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -field_amplitude=0.60e6 -output%name+=negative_decay_15mm/neg_EL15mm_ER1.5mm_0.60e6





#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.574938e6 -output%name+=plate_electrode/neg_EL3mm_ER0.3mm_1.574938e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.574940e6 -output%name+=plate_electrode/neg_EL3mm_ER0.3mm_1.574940e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.574942e6 -output%name+=plate_electrode/neg_EL3mm_ER0.3mm_1.574942e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.574944e6 -output%name+=plate_electrode/neg_EL3mm_ER0.3mm_1.574944e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.574946e6 -output%name+=plate_electrode/neg_EL3mm_ER0.3mm_1.574946e6





#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.456466e6 -output%name+=plate_electrode/neg_EL4mm_ER0.4mm_1.456466e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.456469e6 -output%name+=plate_electrode/neg_EL4mm_ER0.4mm_1.456469e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.456472e6 -output%name+=plate_electrode/neg_EL4mm_ER0.4mm_1.456472e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.456475e6 -output%name+=plate_electrode/neg_EL4mm_ER0.4mm_1.456475e6


#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.456475e6 -output%name+=plate_electrode/neg_EL4mm_ER0.4mm_1.456475e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.456480e6 -output%name+=plate_electrode/neg_EL4mm_ER0.4mm_1.456480e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.456485e6 -output%name+=plate_electrode/neg_EL4mm_ER0.4mm_1.456485e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.456490e6 -output%name+=plate_electrode/neg_EL4mm_ER0.4mm_1.456490e6




#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.5e-3 -field_amplitude=0.905e6 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/domain_250mm/neg_EL24mm_ER2.5mm_0.905e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.5e-3 -field_amplitude=0.910e6 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/domain_250mm/neg_EL24mm_ER2.5mm_0.910e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.5e-3 -field_amplitude=0.915e6 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/domain_250mm/neg_EL24mm_ER2.5mm_0.915e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.5e-3 -field_amplitude=0.920e6 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/domain_250mm/neg_EL24mm_ER2.5mm_0.920e6

#./streamer air_negative_250mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=2.5e-3 -field_amplitude=0.925e6 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/domain_250mm/neg_EL24mm_ER2.5mm_0.925e6





#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.2706416e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.317e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.2716064e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.318e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.35072e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.400e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.3526496e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.402e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.3545792e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.404e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.4298336e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.482e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.4307984e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.483e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.4317632e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.484e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.432728e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.485e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.4443056e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.497e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.4481648e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.501e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.4491296e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.502e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.45221696e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.5052e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.45385712e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.5069e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.4554008e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.5085e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.45549728e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.5086e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.45559376e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.5087e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.4558832e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.5090e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.45597968e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.5091e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.45607616e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.5092e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.456848e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.5100e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.45694448e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.5101e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -field_amplitude=1.45704096e6 -output%name=/export/scratch2/md/baohong/negative_decay_4mm/neg_EL4mm_ER0.4mm_1.5102e6






#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%min_field=0.91874048e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_exponentially_decay_2mm/neg_EL2mm_ER0.2mm_2.0e6_0.9352e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%min_field=1.16728768e6 -output%name=/export/scratch2/md/baohong/negative_exponentially_decay_2mm/neg_EL2mm_ER0.2mm_2.0e6_1.1882e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%min_field=1.26179456e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_exponentially_decay_2mm/neg_EL2mm_ER0.2mm_2.0e6_1.2844e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%min_field=1.33203616e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_exponentially_decay_2mm/neg_EL2mm_ER0.2mm_2.0e6_1.3559e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%min_field=1.36907264e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_exponentially_decay_2mm/neg_EL2mm_ER0.2mm_2.0e6_1.3936e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%min_field=1.57184e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_exponentially_decay_2mm/neg_EL2mm_ER0.2mm_2.0e6_1.60e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%min_field=1.9648e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_exponentially_decay_2mm/neg_EL2mm_ER0.2mm_2.0e6_2.0e6_5e-3_115.1e-3

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_decay%enabled=T -field_decay%min_field=1.37359168e6 -output%name=/export/scratch2/md/baohong/negative_exponentially_decay_2mm/neg_EL2mm_ER0.2mm_2.0e6_1.3982e6_5e-3_115.1e-3



#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.753200864e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.78461e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.753210688e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.78462e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.753220512e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.78463e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.753230336e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.78464e6


#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_time=250e-9 -field_amplitude=1.75843970848e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.7899427e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_time=250e-9 -field_amplitude=1.75843980672e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.7899428e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_time=250e-9 -field_amplitude=1.75843990496e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/negative_decay_2mm/neg_EL2mm_ER0.2mm_1.7899429e6



./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -dt_min=1e-18 -field_amplitude=-1.08064e6 -output%name=/export/scratch3/baohong/afivo-streamer/negative_2d/output/domain_125mm/electrode/air/electro2mm_constant/pos_EL2mm_ER0.2mm_1.1e6_dt1e-18
