#!/bin/bash

cd ../

# air, background density=1e11, electrode length=12e-3, electode radius=1.2e-3, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt


# negative streamers propagation under constant electric field with long electrode


./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=1.246e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_neg/neg_bd1e11_EL12mm_1.4e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=1.424e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_neg/neg_bd1e11_EL12mm_1.6e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=1.602e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_neg/neg_bd1e11_EL12mm_1.8e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=1.78e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_neg/neg_bd1e11_EL12mm_2.0e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=1.958e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_neg/neg_bd1e11_EL12mm_2.2e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=2.136e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_neg/neg_bd1e11_EL12mm_2.4e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=2.314e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_neg/neg_bd1e11_EL12mm_2.6e6


# positive streamers propagation under constant electric field with long electrode


./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=-1.246e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_pos/pos_bd1e11_EL12mm_1.4e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=-1.424e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_pos/pos_bd1e11_EL12mm_1.6e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=-1.602e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_pos/pos_bd1e11_EL12mm_1.8e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=-1.78e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_pos/pos_bd1e11_EL12mm_2.0e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=-1.958e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_pos/pos_bd1e11_EL12mm_2.2e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=-2.136e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_pos/pos_bd1e11_EL12mm_2.4e6

./streamer air_negative_120mm_chem_electro12mm.cfg -field_amplitude=-2.314e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=4300 -lineout%write=T -output%name+=bd1e11_EL12mm_ER1.2mm_constant_pos/pos_bd1e11_EL12mm_2.6e6



# air, background density=1e11, electrode length=3e-3, electode radius=1e-3, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt


# negative streamers propagation under constant electric field with short electrode


./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=1.546667e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_neg/neg_bd1e11_EL3mm_1.6e6

./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=1.74e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_neg/neg_bd1e11_EL3mm_1.8e6

./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=1.933333e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_neg/neg_bd1e11_EL3mm_2.0e6

./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=2.126667e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_neg/neg_bd1e11_EL3mm_2.2e6

./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=2.32e6 -output%dt=2e-10 -field_decay%enabled=F  -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_neg/neg_bd1e11_EL3mm_2.4e6

./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=2.513333e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_neg/neg_bd1e11_EL3mm_2.6e6


# positive streamers propagation under constant electric field with short electrode


./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=-1.546667e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_pos/pos_bd1e11_EL3mm_1.6e6

./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=-1.74e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_pos/pos_bd1e11_EL3mm_1.8e6

./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=-1.933333e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_pos/pos_bd1e11_EL3mm_2.0e6

./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=-2.126667e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_pos/pos_bd1e11_EL3mm_2.2e6

./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=-2.32e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_pos/pos_bd1e11_EL3mm_2.4e6

./streamer air_negative_120mm_chem_electro3mm.cfg -field_amplitude=-2.513333e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3700 -lineout%write=T -output%name+=bd1e11_EL3mm_ER1mm_constant_pos/pos_bd1e11_EL3mm_2.6e6


# air, background density=0, seed density=5e19, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt


# negative streamers propagation under constant electric field without electrode


./streamer air_negative_120mm_chem_noelectro.cfg -field_amplitude=2.0e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3500 -lineout%write=T -output%name=output/domain_120mm/no_electrode/air/sd5e19_constant_neg/neg_sd5e19_2.0e6

./streamer air_negative_120mm_chem_noelectro.cfg -field_amplitude=2.2e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3500 -lineout%write=T -output%name=output/domain_120mm/no_electrode/air/sd5e19_constant_neg/neg_sd5e19_2.2e6

./streamer air_negative_120mm_chem_noelectro.cfg -field_amplitude=2.4e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3500 -lineout%write=T -output%name=output/domain_120mm/no_electrode/air/sd5e19_constant_neg/neg_sd5e19_2.4e6

./streamer air_negative_120mm_chem_noelectro.cfg -field_amplitude=2.6e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3500 -lineout%write=T -output%name=output/domain_120mm/no_electrode/air/sd5e19_constant_neg/neg_sd5e19_2.6e6


# positive streamers propagation under constant electric field without electrode


./streamer air_negative_120mm_chem_noelectro.cfg -field_amplitude=-2.0e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3500 -lineout%write=T -output%name=output/domain_120mm/no_electrode/air/sd5e19_constant_pos/pos_sd5e19_2.0e6

./streamer air_negative_120mm_chem_noelectro.cfg -field_amplitude=-2.2e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3500 -lineout%write=T -output%name=output/domain_120mm/no_electrode/air/sd5e19_constant_pos/pos_sd5e19_2.2e6

./streamer air_negative_120mm_chem_noelectro.cfg -field_amplitude=-2.4e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3500 -lineout%write=T -output%name=output/domain_120mm/no_electrode/air/sd5e19_constant_pos/pos_sd5e19_2.4e6

./streamer air_negative_120mm_chem_noelectro.cfg -field_amplitude=-2.6e6 -output%dt=2e-10 -field_decay%enabled=F -cross%write=T -cross%npoints=3500 -lineout%write=T -output%name=output/domain_120mm/no_electrode/air/sd5e19_constant_pos/pos_sd5e19_2.6e6



