#!/bin/bash

cd ../

# air, background density=1e11, constant applied electric field, output%dt=5e-10, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt


#The stable streamers is quite sensitive to the electric field at electrode 2mm


#0.99997 Estable
./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -end_time=250e-9 -field_amplitude=1.75841632736e6 -cross%write=T -output%name+=negative_stable_electro2mm_unstable/neg_EL2mm_ER0.2mm_1.7899189e6

#0.99998 Estable
./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -end_time=250e-9 -field_amplitude=1.75843391232e6 -cross%write=T -output%name+=negative_stable_electro2mm_unstable/neg_EL2mm_ER0.2mm_1.7899368e6

#0.99999 Estable
./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -end_time=250e-9 -field_amplitude=1.75845149728e6 -cross%write=T -output%name+=negative_stable_electro2mm_unstable/neg_EL2mm_ER0.2mm_1.7899547e6

#Estable
./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.75846908224e6 -cross%write=T -output%name+=negative_stable_electro2mm_unstable/neg_EL2mm_ER0.2mm_1.7899726e6

#1.00001 Estable
./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.7584866672e6 -cross%write=T -output%name+=negative_stable_electro2mm_unstable/neg_EL2mm_ER0.2mm_1.7899905e6

#1.00002 Estable
./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.75850425216e6 -cross%write=T -output%name+=negative_stable_electro2mm_unstable/neg_EL2mm_ER0.2mm_1.7900084e6

#1.00003 Estable
./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.75852183712e6 -cross%write=T -output%name+=negative_stable_electro2mm_unstable/neg_EL2mm_ER0.2mm_1.7900263e6









