#!/bin/bash

# This is an example to show how you can run multiple simulations after each  other

# Change a certain parameter

cd ../

#background density=1e15, seed density=7.5e18
#./streamer CO2_negative.cfg  -field_decay%min_field=0.8e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.8e6_15e-3_60e-3

#./streamer CO2_negative.cfg  -field_decay%min_field=0.6e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.6e6_15e-3_60e-3

#./streamer CO2_negative.cfg  -field_decay%min_field=0.4e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.4e6_15e-3_60e-3

#./streamer CO2_negative.cfg  -field_decay%min_field=0.3e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.3e6_15e-3_60e-3

#./streamer CO2_negative.cfg  -field_decay%min_field=0.2e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.2e6_15e-3_60e-3

#./streamer CO2_negative.cfg  -field_decay%min_field=0.1e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.1e6_15e-3_60e-3


#background density=1e15, seed density=5e19
./streamer CO2_negative.cfg  -field_decay%min_field=0.6e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.6e6_15e-3_60e-3

./streamer CO2_negative.cfg  -field_decay%min_field=0.4e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.4e6_15e-3_60e-3

./streamer CO2_negative.cfg  -field_decay%min_field=0.3e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.3e6_15e-3_60e-3

./streamer CO2_negative.cfg  -field_decay%min_field=0.2e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.2e6_15e-3_60e-3

./streamer CO2_negative.cfg  -field_decay%min_field=0.1e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.1e6_15e-3_60e-3

./streamer CO2_negative.cfg  -field_decay%min_field=0.05e6 -output%name+=exponential/min_field/dirichlet_1.8e6_0.05e6_15e-3_60e-3





