#!/bin/bash

cd ../

./streamer air_negative_v125mm.cfg -field_decay%min_field=1.3e6 -field_decay%decay_distance=5e-3 -refine_min_dx=1e-6 -refine_adx=1 -refine_adx_fac=1 -output%name+=exponential/min_field/chemistry_style/sd5e19_2.1e6_5e-3_145e-3/50points_runtime/1.3e6_oldstyle_mindx1e-6_adx1_fac1_125mm

#./streamer air_negative_v160mm.cfg -field_decay%min_field=1.3e6 -field_decay%decay_distance=5e-3 -refine_min_dx=1e-6 -refine_adx=1 -refine_adx_fac=1 -output%name+=exponential/min_field/chemistry_style/sd5e19_2.1e6_5e-3_145e-3/50points_runtime/1.3e6_oldstyle_mindx1e-6_adx1_fac1_160mm

./streamer air_negative_chemistry_v125mm.cfg -field_decay%min_field=1.25e6 -field_decay%decay_distance=5e-3 -refine_min_dx=1e-6 -refine_adx=1 -refine_adx_fac=1 -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_50points.txt -output%name+=exponential/min_field/chemistry_style/sd5e19_2.1e6_5e-3_145e-3/50points_runtime/1.25e6_chemistry50points_mindx1e-6_adx1_fac1_125mm

#./streamer air_negative_chemistry_v160mm.cfg -field_decay%min_field=1.25e6 -field_decay%decay_distance=5e-3 -refine_min_dx=1e-6 -refine_adx=1 -refine_adx_fac=1 -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_50points.txt -output%name+=exponential/min_field/chemistry_style/sd5e19_2.1e6_5e-3_145e-3/50points_runtime/1.25e6_chemistry50points_mindx1e-6_adx1_fac1_160mm