#!/bin/bash

cd ../

# air, background density=1e11, electrode length=9e-3, electode radius=0.9e-3, output%dt=5e-10, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points_recomb.txt


./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=10.08e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_126kV_recomb

./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=10.24e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_128kV_recomb

./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=10.4e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_130kV_recomb

./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=10.56e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_132kV_recomb

./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=10.72e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_134kV_recomb

./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=10.88e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_136kV_recomb

./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=11.04e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_138kV_recomb

./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=11.2e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_140kV_recomb

./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=11.36e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_142kV_recomb

./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=11.52e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_144kV_recomb

./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=11.688e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_146.1kV_recomb

# steady streamer
./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=11.752e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_146.9kV_recomb

./streamer air_negative_125mm_chem_electro9mm.cfg -field_amplitude=12.96e5 -cross%write=T -plane%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_1000points_recomb.txt -output%name+=neg_EL9mm_decay_recombination/neg_EL9mm_162kV_recomb




