#!/bin/bash

cd ../

# air, bd=1e11, electrode_3mm_1mm, refine_min_dx=1e-6, refine_adx=1, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt

# the fading out of negative streamers under exponentially decaying electric field (short electrode)
./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=1.40e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.40e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=1.38e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.38e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=1.376e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.376e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=1.374e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.374e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=1.37e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.37e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg  -field_decay%enabled=T -field_decay%min_field=1.368e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.368e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg  -field_decay%enabled=T -field_decay%min_field=1.36e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.36e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=1.35e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.35e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=1.33e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.33e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=1.30e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.30e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=1.26e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.26e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=1.2e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.2e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=1.1e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_1.1e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=0.9e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_0.9e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=0.6e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_0.6e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=0.3e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_0.3e6_5e-3

./streamer air_negative_120mm_chem_electro3mm.cfg -field_decay%enabled=T -field_decay%min_field=0e6 -cross%write=T -output%name+=bd1e11_EL3mm_ER1mm_decay_neg/neg_bd1e11_3mm_1mm_1.6e6_0e6_5e-3


