#!/bin/bash

cd ../

# air, background density=1e11, electrode length=3e-3, electode radius=0.3e-3, output%dt=5e-10, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt



./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=0.71549864e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_0.7349e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=0.95159664e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_0.9774e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.04915136e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.0776e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.10104424e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.1309e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.13297832e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.1637e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.153716e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.1850e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.16754112e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.1992e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.17669296e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.2086e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.1838976e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.2160e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.19275736e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.2251e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.20473264e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.2374e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.219434e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.2525e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.55776e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.6e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.9472e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_2.0e6_5e-3_115.1e-3

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -output%dt=1e-10 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.55776e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.6e6_5e-3_115.1e-3_dt1e-10

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -output%dt=1e-10 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.9472e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_2.0e6_5e-3_115.1e-3_dt1e-10



