#!/bin/bash

cd ../

# air, background density=1e11, EL=2-21mm, output%dt=5e-10, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt


./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=100e-3 -field_amplitude=17.584688e5 -cross%write=T -plane%write=T -output%name+=neg_EL2-21mm_steady/neg_EL2mm_219.8086kV

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=100e-3 -field_amplitude=15.74936e5 -cross%write=T -plane%write=T -output%name+=neg_EL2-21mm_steady/neg_EL3mm_196.867kV

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -end_streamer_length=100e-3 -field_amplitude=14.5648e5 -cross%write=T -plane%write=T -output%name+=neg_EL2-21mm_steady/neg_EL4mm_182.06kV

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.96" -field_rod_radius=0.5e-3 -end_streamer_length=100e-3 -field_amplitude=13.696e5 -cross%write=T -plane%write=T -output%name+=neg_EL2-21mm_steady/neg_EL5mm_171.20kV

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -end_streamer_length=95e-3 -field_amplitude=12.4976e5 -cross%write=T -plane%write=T -output%name+=neg_EL2-21mm_steady/neg_EL7mm_156.22kV

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=95e-3 -field_amplitude=11.688e5 -cross%write=T -plane%write=T -output%name+=neg_EL2-21mm_steady/neg_EL9mm_146.1kV

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -end_streamer_length=90e-3 -field_amplitude=10.808e5 -cross%write=T -plane%write=T -output%name+=neg_EL2-21mm_steady/neg_EL12mm_135.1kV

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -end_streamer_length=85e-3 -field_amplitude=10.168e5 -cross%write=T -plane%write=T -output%name+=neg_EL2-21mm_steady/neg_EL15mm_127.1kV

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.856" -field_rod_radius=1.8e-3 -end_streamer_length=85e-3 -field_amplitude=9.664e5 -cross%write=T -plane%write=T -output%name+=neg_EL2-21mm_steady/neg_EL18mm_120.8kV

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=80e-3 -field_amplitude=9.232e5 -cross%write=T -plane%write=T -output%name+=neg_EL2-21mm_steady/neg_EL21mm_115.4kV





