#!/bin/bash

cd ../

# air, background density=1e11, domain_len=0.3, seed_density=5e19, seed_length=4.2e-3, seed_width=0.42e-3, output%dt=5e-10, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt

#./streamer air_negative_300mm_chem_neutral_seed.cfg -seed_rel_r1="0 0.985" -seed_width=4.5e-4 -field_amplitude=1.56943917e6 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_SL4.5mm_sd5e19_470.831751kV

#./streamer air_negative_300mm_chem_neutral_seed.cfg -seed_rel_r1="0 0.986" -seed_width=4.2e-4 -field_amplitude=1.599619124e6 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_SL4.2mm_sd5e19_479.8857372kV



# air, background density=1e11, domain_len=0.3, EL=3-24mm, output%dt=5e-10, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt

./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.99" -field_rod_radius=0.3e-3 -field_amplitude=15.75129076667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL3mm_472.538723kV

./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.986667" -field_rod_radius=0.4e-3 -field_amplitude=14.5578773333e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL4mm_436.73632kV

./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.983333" -field_rod_radius=0.5e-3 -field_amplitude=13.69406667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL5mm_410.822kV

./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="280 280" -field_rod_r0="0 0.976667" -field_rod_radius=0.7e-3 -field_amplitude=12.513e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL7mm_375.39kV

./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="320 320" -field_rod_r0="0 0.97" -field_rod_radius=0.9e-3 -field_amplitude=11.7336667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL9mm_352.01kV

./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="360 360" -field_rod_r0="0 0.96" -field_rod_radius=1.2e-3 -field_amplitude=10.8736667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL12mm_326.21kV

./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="360 360" -field_rod_r0="0 0.95" -field_rod_radius=1.5e-3 -field_amplitude=10.294e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL15mm_308.82kV

./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="160 160" -field_rod_r0="0 0.94" -field_rod_radius=1.8e-3 -field_amplitude=9.834e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL18mm_295.02kV

./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.93" -field_rod_radius=2.1e-3 -field_amplitude=9.48e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL21mm_284.4kV

./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.92" -field_rod_radius=2.4e-3 -field_amplitude=9.193333e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL24mm_275.8kV

./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.92" -field_rod_radius=2.4e-3 -field_amplitude=9.193333e5 -cross%write=T -cross%npoints=10000  -cross%rmax=0.021 -plane%write=T -plane%npixels="700 10000" -plane%rmax="0.07 1" -output%name+=neg_d300mm_steady/neg_EL24mm_275.8kV_fineaxis


# other coarse grid size, the results are not so good for fitting  Rmin

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976667" -field_rod_radius=0.7e-3 -field_amplitude=12.50503333e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL7mm_375.151kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="200 200" -field_rod_r0="0 0.97" -field_rod_radius=0.9e-3 -field_amplitude=11.7216667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL9mm_351.65kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.97" -field_rod_radius=0.9e-3 -field_amplitude=11.694e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL9mm_350.82kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="280 280" -field_rod_r0="0 0.97" -field_rod_radius=0.9e-3 -field_amplitude=11.7376667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL9mm_352.13kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.96" -field_rod_radius=1.2e-3 -field_amplitude=10.908e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL12mm_327.24kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="160 160" -field_rod_r0="0 0.96" -field_rod_radius=1.2e-3 -field_amplitude=10.865e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL12mm_325.95kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="240 240" -field_rod_r0="0 0.96" -field_rod_radius=1.2e-3 -field_amplitude=10.8893333e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL12mm_326.68kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="112 112" -field_rod_r0="0 0.95" -field_rod_radius=1.5e-3 -field_amplitude=10.307e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL15mm_309.21kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="280 280" -field_rod_r0="0 0.95" -field_rod_radius=1.5e-3 -field_amplitude=10.2676667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL15mm_308.03kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.94" -field_rod_radius=1.8e-3 -field_amplitude=9.817e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL18mm_294.51kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="160 160" -field_rod_r0="0 0.93" -field_rod_radius=2.1e-3 -field_amplitude=9.4643333e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL21mm_283.93kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="200 200" -field_rod_r0="0 0.92" -field_rod_radius=2.4e-3 -field_amplitude=9.216667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL24mm_276.5kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.916667" -field_rod_radius=2.5e-3 -field_amplitude=9.103333e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL25mm_273.1kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="80 80" -field_rod_r0="0 0.916667" -field_rod_radius=2.5e-3 -field_amplitude=9.106667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL25mm_273.2kV

