#!/bin/bash

# This is an example to show how you can run multiple simulations after each  other

# Change a certain parameter

cd ../

./streamer air_negative_v80mm.cfg  -field_decay%min_field=2.0e6 -output%name+=step/min_field/2.5e6_2.0e6_60e-3

./streamer air_negative_v80mm.cfg  -field_decay%min_field=1.8e6 -output%name+=step/min_field/2.5e6_1.8e6_60e-3

./streamer air_negative_v80mm.cfg  -field_decay%min_field=1.6e6 -output%name+=step/min_field/2.5e6_1.6e6_60e-3

./streamer air_negative_v80mm.cfg  -field_decay%min_field=1.5e6 -output%name+=step/min_field/2.5e6_1.5e6_60e-3

./streamer air_negative_v80mm.cfg  -field_decay%min_field=1.44e6 -output%name+=step/min_field/2.5e6_1.44e6_60e-3

./streamer air_negative_v80mm.cfg  -field_decay%min_field=1.4e6 -output%name+=step/min_field/2.5e6_1.4e6_60e-3
