#!/bin/bash

# This is an example to show how you can run multiple simulations after each other

cd ../

# bd=1e9, EL18mm, refine_min_dx=2e-6, refine_adx=1, refine_adx_fac=1.2, chemistry_transport_data_300points

./streamer air_negative_chemistry_v120mm_electrode.cfg -field_rod_radius=0.5e-3 -field_amplitude=0.9e6 -field_decay%enabled=F -cross%write=F -output%name+=constant/bd1e9_EL18mm/bd1e9_18mm_0.5mm_0.9e6

./streamer air_negative_chemistry_v120mm_electrode.cfg -field_rod_radius=1e-3 -field_amplitude=0.9e6 -field_decay%enabled=F -cross%write=F -output%name+=constant/bd1e9_EL18mm/bd1e9_18mm_1mm_0.9e6

./streamer air_negative_chemistry_v120mm_electrode.cfg -field_rod_radius=1.5e-3 -field_amplitude=0.9e6 -field_decay%enabled=F -cross%write=F -output%name+=constant/bd1e9_EL18mm/bd1e9_18mm_1.5mm_0.9e6

./streamer air_negative_chemistry_v120mm_electrode.cfg -field_rod_radius=2e-3 -field_amplitude=0.91e6 -field_decay%enabled=F -cross%write=F -output%name+=constant/bd1e9_EL18mm/bd1e9_18mm_2mm_0.91e6

#./streamer air_negative_chemistry_v120mm_electrode.cfg -field_rod_radius=2.5e-3 -field_amplitude=1.1e6 -field_decay%enabled=F -cross%write=F -output%name+=constant/bd1e9_EL18mm/bd1e9_18mm_2.5mm_1.1e6

./streamer air_negative_chemistry_v120mm_electrode.cfg -field_rod_radius=3e-3 -field_amplitude=0.92e6 -field_decay%enabled=F -cross%write=F -output%name+=constant/bd1e9_EL18mm/bd1e9_18mm_3mm_0.92e6

#./streamer air_negative_chemistry_v120mm_electrode.cfg -field_rod_radius=5e-3 -field_amplitude=0.99e6 -field_decay%enabled=F -cross%write=F -output%name+=constant/bd1e9_EL18mm/bd1e9_18mm_5mm_0.99e6

./streamer air_negative_chemistry_v120mm_electrode.cfg -field_rod_radius=10e-3 -field_amplitude=1.0e6 -field_decay%enabled=F -cross%write=F -output%name+=constant/bd1e9_EL18mm/bd1e9_18mm_10mm_1.0e6

./streamer air_negative_chemistry_v120mm_electrode.cfg -field_rod_radius=18e-3 -field_amplitude=1.05e6 -field_decay%enabled=F -cross%write=F -output%name+=constant/bd1e9_EL18mm/bd1e9_18mm_18mm_1.05e6


