#!/bin/bash

# This is an example to show how you can run multiple simulations after each  other

# Change a certain parameter

cd ../

./streamer air_positive.cfg  -field_decay%min_field=0.6e6 -output%name+=exponential/min_field/neumann_2.0e6_0.6e6_15e-3_60e-3

./streamer air_positive.cfg  -field_decay%min_field=0.5e6 -output%name+=exponential/min_field/neumann_2.0e6_0.5e6_15e-3_60e-3

./streamer air_positive.cfg  -field_decay%min_field=0.4e6 -output%name+=exponential/min_field/neumann_2.0e6_0.4e6_15e-3_60e-3

./streamer air_positive.cfg  -field_decay%min_field=0.3e6 -output%name+=exponential/min_field/neumann_2.0e6_0.3e6_15e-3_60e-3

./streamer air_positive.cfg  -field_decay%min_field=0.2e6 -output%name+=exponential/min_field/neumann_2.0e6_0.2e6_15e-3_60e-3

./streamer air_positive.cfg  -field_decay%min_field=0.1e6 -output%name+=exponential/min_field/neumann_2.0e6_0.1e6_15e-3_60e-3




