#!/bin/bash

cd ../

# air, background density=1e11, electrode length=12e-3, electode radius=1.2e-3, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt


# electrode size


#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=1e-3 -field_amplitude=1.57784e6 -output%name+=electrode_size/neg_EL3mm_ER1mm_1.63e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.8e-3 -field_amplitude=1.580448e6 -output%name+=electrode_size/neg_EL3mm_ER0.8mm_1.63e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.6e-3 -field_amplitude=1.583056e6 -output%name+=electrode_size/neg_EL3mm_ER0.6mm_1.63e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.4e-3 -field_amplitude=1.585664e6 -output%name+=electrode_size/neg_EL3mm_ER0.4mm_1.63e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.586968e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.63e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.976" -field_rod_radius=0.2e-3 -field_amplitude=1.588272e6 -output%name+=electrode_size/neg_EL3mm_ER0.2mm_1.63e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.976" -field_rod_radius=0.1e-3 -field_amplitude=1.589576e6 -output%name+=electrode_size/neg_EL3mm_ER0.1mm_1.63e6


#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=1e-3 -field_amplitude=1.5488e6 -output%name+=electrode_size/neg_EL3mm_ER1mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.8e-3 -field_amplitude=1.55136e6 -output%name+=electrode_size/neg_EL3mm_ER0.8mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.6e-3 -field_amplitude=1.55392e6 -output%name+=electrode_size/neg_EL3mm_ER0.6mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.4e-3 -field_amplitude=1.55648e6 -output%name+=electrode_size/neg_EL3mm_ER0.4mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.55776e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.976" -field_rod_radius=0.2e-3 -field_amplitude=1.55904e6 -output%name+=electrode_size/neg_EL3mm_ER0.2mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.976" -field_rod_radius=0.1e-3 -field_amplitude=1.56032e6 -output%name+=electrode_size/neg_EL3mm_ER0.1mm_1.6e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.984" -field_rod_radius=0.8e-3 -field_amplitude=1.56416e6 -output%name+=electrode_size/neg_EL2mm_ER0.8mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.984" -field_rod_radius=0.6e-3 -field_amplitude=1.56672e6 -output%name+=electrode_size/neg_EL2mm_ER0.6mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.4e-3 -field_amplitude=1.56928e6 -output%name+=electrode_size/neg_EL2mm_ER0.4mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.3e-3 -field_amplitude=1.57056e6 -output%name+=electrode_size/neg_EL2mm_ER0.3mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.57184e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.1e-3 -field_amplitude=1.57312e6 -output%name+=electrode_size/neg_EL2mm_ER0.1mm_1.6e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.988" -field_rod_radius=0.6e-3 -field_amplitude=1.62228e6 -output%name+=electrode_size/neg_EL1.5mm_ER0.6mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.988" -field_rod_radius=0.5e-3 -field_amplitude=1.6236e6 -output%name+=electrode_size/neg_EL1.5mm_ER0.5mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.988" -field_rod_radius=0.3e-3 -field_amplitude=1.62624e6 -output%name+=electrode_size/neg_EL1.5mm_ER0.3mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.988" -field_rod_radius=0.2e-3 -field_amplitude=1.62756e6 -output%name+=electrode_size/neg_EL1.5mm_ER0.2mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.988" -field_rod_radius=0.15e-3 -field_amplitude=1.62822e6 -output%name+=electrode_size/neg_EL1.5mm_ER0.15mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.988" -field_rod_radius=0.1e-3 -field_amplitude=1.62888e6 -output%name+=electrode_size/neg_EL1.5mm_ER0.1mm_1.65e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.99" -field_rod_radius=0.6e-3 -field_amplitude=1.62558e6 -output%name+=electrode_size/neg_EL1.25mm_ER0.6mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.99" -field_rod_radius=0.4e-3 -field_amplitude=1.62822e6 -output%name+=electrode_size/neg_EL1.25mm_ER0.4mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.99" -field_rod_radius=0.3e-3 -field_amplitude=1.62954e6 -output%name+=electrode_size/neg_EL1.25mm_ER0.3mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.99" -field_rod_radius=0.2e-3 -field_amplitude=1.63086e6 -output%name+=electrode_size/neg_EL1.25mm_ER0.2mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.99" -field_rod_radius=0.125e-3 -field_amplitude=1.63185e6 -output%name+=electrode_size/neg_EL1.25mm_ER0.125mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.99" -field_rod_radius=0.1e-3 -field_amplitude=1.63218e6 -output%name+=electrode_size/neg_EL1.25mm_ER0.1mm_1.65e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.992" -field_rod_radius=0.5e-3 -field_amplitude=1.6302e6 -output%name+=electrode_size/neg_EL1mm_ER0.5mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.992" -field_rod_radius=0.25e-3 -field_amplitude=1.6335e6 -output%name+=electrode_size/neg_EL1mm_ER0.25mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=1.63416e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.992" -field_rod_radius=0.15e-3 -field_amplitude=1.63482e6 -output%name+=electrode_size/neg_EL1mm_ER0.15mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.992" -field_rod_radius=0.1e-3 -field_amplitude=1.63548e6 -output%name+=electrode_size/neg_EL1mm_ER0.1mm_1.65e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.996" -field_rod_radius=0.5e-3 -field_amplitude=1.6368e6 -output%name+=electrode_size/neg_EL0.5mm_ER0.5mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.996" -field_rod_radius=0.25e-3 -field_amplitude=1.6401e6 -output%name+=electrode_size/neg_EL0.5mm_ER0.25mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.996" -field_rod_radius=0.2e-3 -field_amplitude=1.64076e6 -output%name+=electrode_size/neg_EL0.5mm_ER0.2mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.996" -field_rod_radius=0.125e-3 -field_amplitude=1.64175e6 -output%name+=electrode_size/neg_EL0.5mm_ER0.125mm_1.65e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.996" -field_rod_radius=0.1e-3 -field_amplitude=1.64208e6 -output%name+=electrode_size/neg_EL0.5mm_ER0.1mm_1.65e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1620496e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.262e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1638912e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.264e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.164812e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.265e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1657328e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.266e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1675744e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.268e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1684952e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.269e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.169416e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.27e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1703368e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.271e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.1712576e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.272e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.17402e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.275e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.178624e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.28e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.183228e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.285e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -field_amplitude=1.187832e6 -output%name+=electrode_size/neg_EL9mm_ER0.9mm_1.29e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.936" -field_rod_radius=0.8e-3 -field_amplitude=1.152704e6 -output%name+=electrode_size/neg_EL8mm_ER0.8mm_1.24e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.936" -field_rod_radius=0.8e-3 -field_amplitude=1.162e6 -output%name+=electrode_size/neg_EL8mm_ER0.8mm_1.25e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.936" -field_rod_radius=0.8e-3 -field_amplitude=1.171296e6 -output%name+=electrode_size/neg_EL8mm_ER0.8mm_1.26e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.936" -field_rod_radius=0.8e-3 -field_amplitude=1.180592e6 -output%name+=electrode_size/neg_EL8mm_ER0.8mm_1.27e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.936" -field_rod_radius=0.8e-3 -field_amplitude=1.189888e6 -output%name+=electrode_size/neg_EL8mm_ER0.8mm_1.28e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.936" -field_rod_radius=0.8e-3 -field_amplitude=1.199184e6 -output%name+=electrode_size/neg_EL8mm_ER0.8mm_1.29e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.936" -field_rod_radius=0.8e-3 -field_amplitude=1.2010432e6 -output%name+=electrode_size/neg_EL8mm_ER0.8mm_1.292e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.936" -field_rod_radius=0.8e-3 -field_amplitude=1.2029024e6 -output%name+=electrode_size/neg_EL8mm_ER0.8mm_1.294e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.936" -field_rod_radius=0.8e-3 -field_amplitude=1.2047616e6 -output%name+=electrode_size/neg_EL8mm_ER0.8mm_1.296e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.936" -field_rod_radius=0.8e-3 -field_amplitude=1.2066208e6 -output%name+=electrode_size/neg_EL8mm_ER0.8mm_1.298e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.572364e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.615e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.5733376e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.616e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.57489536e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.6176e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.574914832e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.61762e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.57494404e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.61765e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.574934304e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.61764e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.574924568e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.61763e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.574953776e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.61766e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.57499272e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.6177e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.57509008e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.6178e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.57518744e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.6179e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.5743112e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.617e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.5752848e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.618e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.5762584e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.619e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.577232e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.62e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.5821e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.625e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.586968e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.63e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.591836e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.635e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.596704e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.64e6


#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.952" -field_rod_radius=1.5e-3 -field_amplitude=1.2643e6 -output%name+=electrode_size/neg_EL6mm_ER1.5mm_1.345e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.952" -field_rod_radius=1.2e-3 -field_amplitude=1.27224e6 -output%name+=electrode_size/neg_EL6mm_ER1.2mm_1.35e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.952" -field_rod_radius=0.9e-3 -field_amplitude=1.280204e6 -output%name+=electrode_size/neg_EL6mm_ER0.9mm_1.355e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.952" -field_rod_radius=0.8e-3 -field_amplitude=1.286016e6 -output%name+=electrode_size/neg_EL6mm_ER0.8mm_1.36e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.952" -field_rod_radius=0.7e-3 -field_amplitude=1.291836e6 -output%name+=electrode_size/neg_EL6mm_ER0.7mm_1.365e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.952" -field_rod_radius=0.6e-3 -field_amplitude=1.297664e6 -output%name+=electrode_size/neg_EL6mm_ER0.6mm_1.37e6


#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=1.0e-3 -field_amplitude=1.52944e6 -output%name+=electrode_size/neg_EL3mm_ER1.0mm_1.58e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.8e-3 -field_amplitude=1.541664e6 -output%name+=electrode_size/neg_EL3mm_ER0.8mm_1.59e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.6e-3 -field_amplitude=1.55392e6 -output%name+=electrode_size/neg_EL3mm_ER0.6mm_1.6e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.4e-3 -field_amplitude=1.566208e6 -output%name+=electrode_size/neg_EL3mm_ER0.4mm_1.61e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -field_amplitude=1.572364e6 -output%name+=electrode_size/neg_EL3mm_ER0.3mm_1.615e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -field_rod_r0="0 0.976" -field_rod_radius=0.2e-3 -field_amplitude=1.57579968e6 -output%name+=electrode_size/neg_EL3mm_ER0.2mm_1.6172e6





#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.753584e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.785e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.3e-3 -field_amplitude=1.752156e6 -output%name+=electrode_size/neg_EL2mm_ER0.3mm_1.785e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.4e-3 -field_amplitude=1.745824e6 -output%name+=electrode_size/neg_EL2mm_ER0.4mm_1.78e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.5e-3 -field_amplitude=1.7444e6 -output%name+=electrode_size/neg_EL2mm_ER0.5mm_1.78e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.6e-3 -field_amplitude=1.733184e6 -output%name+=electrode_size/neg_EL2mm_ER0.6mm_1.77e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.8e-3 -field_amplitude=1.730352e6 -output%name+=electrode_size/neg_EL2mm_ER0.8mm_1.77e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=1.0e-3 -field_amplitude=1.72752e6 -output%name+=electrode_size/neg_EL2mm_ER1.0mm_1.77e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.753584e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.785e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.7565312e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.788e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.75829952e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.7898e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.75839776e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.7899e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.75844688e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.78995e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.7584675104e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.789971e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.7584684928e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.789972e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.7584694752e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.789973e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.7584704576e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.789974e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.75847144e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.789975e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.758476352e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.78998e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.758466528e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.78997e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.758481264e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.789985e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.758461616e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.789965e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.758496e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.79e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.7604608e6 -output%name+=electrode_size/neg_EL2mm_ER0.2mm_1.792e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.08635960512e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.1065828e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.08635970416e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.1065829e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.0863592109408e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.106582402e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.0863592119312e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.106582403e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.086359213912e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.106582405e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.0863592149024e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.106582406e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.0863592178736e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.106582409e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.08635921876496e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.1065824099e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.086359218854096e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.10658240999e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.0863592188630096e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.106582409999e6



#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.08635921529856e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.1065824064e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.08635921519952e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.1065824063e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.08635921510048e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.1065824062e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.08635921500144e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.1065824061e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.08635921569472e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.1065824068e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.086359215556064e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.10658240666e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.0863592155620064e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.106582406666e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.0863592155570544e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.106582406661e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.0863592155580448e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.106582406662e6

#./streamer air_negative_125mm_chem_electro12mm.cfg -coarse_grid_size="512 512" -end_time=300e-9 -field_rod_r0="0 0.992" -field_rod_radius=0.2e-3 -field_amplitude=2.0863592155590352e6 -output%name+=electrode_size/neg_EL1mm_ER0.2mm_2.106582406663e6




#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.64522528e6 -output%name+=negative_decay_2mm/neg_EL2mm_ER0.2mm_1.6747e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.7581698432e6 -output%name+=negative_decay_2mm/neg_EL2mm_ER0.2mm_1.789668e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_time=250e-9 -field_amplitude=1.7583525696e6 -output%name+=negative_decay_2mm/neg_EL2mm_ER0.2mm_1.789854e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_time=250e-9 -field_amplitude=1.75842232e6 -output%name+=negative_decay_2mm/neg_EL2mm_ER0.2mm_1.789925e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.75848951616e6 -output%name+=negative_decay_2mm/neg_EL2mm_ER0.2mm_1.7899934e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.645215456e6 -output%name+=negative_decay_2mm/neg_EL2mm_ER0.2mm_1.67469e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.721646176e6 -output%name+=negative_decay_2mm/neg_EL2mm_ER0.2mm_1.75249e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -field_amplitude=1.7576992736e6 -output%name+=negative_decay_2mm/neg_EL2mm_ER0.2mm_1.789189e6





#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -output%dt=1e-10 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.55776e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_1.6e6_5e-3_115.1e-3_dt1e-10

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -output%dt=1e-10 -field_decay%enabled=T -field_decay%initial_field=1.9472e6 -field_decay%min_field=1.9472e6 -cross%write=T -output%name+=negative_electro3mm_exponentially_decay/neg_EL3mm_ER0.3mm_2.0e6_2.0e6_5e-3_115.1e-3_dt1e-10


#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -end_time=200e-9 -output%dt=1e-10 -field_decay%enabled=T -field_decay%min_field=1.57184e6 -cross%write=T -output%name+=negative_electro2mm_exponentially_decay/neg_EL2mm_ER0.2mm_2.0e6_1.6e6_5e-3_115.1e-3_dt1e-10

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -end_time=200e-9 -output%dt=1e-10 -field_decay%enabled=T -field_decay%min_field=1.9648e6 -cross%write=T -output%name+=negative_electro2mm_exponentially_decay/neg_EL2mm_ER0.2mm_2.0e6_2.0e6_5e-3_115.1e-3_dt1e-10



#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.86656e6 -cross%write=T -output%name+=negative_electro2mm_decay/neg_EL2mm_ER0.2mm_1.9e6


#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.75248e6 -cross%write=T -output%name+=negative_electro3mm_decay/neg_EL3mm_ER0.3mm_1.8e6

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=105e-3 -end_time=200e-9 -field_amplitude=1.84984e6 -cross%write=T -output%name+=negative_electro3mm_decay/neg_EL3mm_ER0.3mm_1.9e6




#./streamer air_negative_125mm_chem_neutral_seed.cfg -field_amplitude=2.07089157e6 -cross%write=T -output%name+=neg_seed2mm_sd5e19_2.07089157e6


#./streamer air_negative_200mm_chem_electro2mm.cfg -field_amplitude=1.7588165343e6 -cross%write=T -output%name+=domain_200mm_EL2mm_stable/neg_EL2mm_ER0.2mm_1.7783787e6

#./streamer air_negative_200mm_chem_electro2mm.cfg -field_amplitude=1.7588166332e6 -cross%write=T -output%name+=domain_200mm_EL2mm_stable/neg_EL2mm_ER0.2mm_1.7783788e6

#./streamer air_negative_200mm_chem_electro2mm.cfg -field_amplitude=1.7588167321e6 -cross%write=T -output%name+=domain_200mm_EL2mm_stable/neg_EL2mm_ER0.2mm_1.7783789e6




#./streamer air_negative_300mm_chem_electro3mm.cfg -field_amplitude=1.575129076e6 -cross%write=F -output%name+=domain_300mm_EL3mm_stable/neg_EL3mm_ER0.3mm_1.575129076e6

#./streamer air_negative_300mm_chem_electro3mm.cfg -field_amplitude=1.575129078e6 -cross%write=F -output%name+=domain_300mm_EL3mm_stable/neg_EL3mm_ER0.3mm_1.575129078e6

#./streamer air_negative_300mm_chem_electro3mm.cfg -field_amplitude=1.575129077e6 -cross%write=F -output%name+=domain_300mm_EL3mm_stable/neg_EL3mm_ER0.3mm_1.575129077e6

#./streamer air_negative_300mm_chem_electro3mm.cfg -field_amplitude=1.575129079e6 -cross%write=F -output%name+=domain_300mm_EL3mm_stable/neg_EL3mm_ER0.3mm_1.575129079e6

#./streamer air_negative_300mm_chem_electro3mm.cfg -field_amplitude=1.57512908e6 -cross%write=F -output%name+=domain_300mm_EL3mm_stable/neg_EL3mm_ER0.3mm_1.57512908e6

#./streamer air_negative_300mm_chem_electro3mm.cfg -field_amplitude=1.575129081e6 -cross%write=F -output%name+=domain_300mm_EL3mm_stable/neg_EL3mm_ER0.3mm_1.575129081e6



#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=100e-3 -field_amplitude=17.704688e5 -cross%write=F -plane%write=F -output%name+=neg_EL2mm_221.3086kV

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=100e-3 -field_amplitude=17.744688e5 -cross%write=F -plane%write=F -output%name+=neg_EL2mm_221.8086kV



cd ../

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.92" -field_rod_radius=2.4e-3 -field_amplitude=9.19333e5 -cross%write=T -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL24mm_275.8kV


#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.94" -field_rod_radius=1.8e-3 -field_amplitude=9.76667e5 -cross%write=T -plane%write=T -table_data%input_interpolation='cubic_spline' -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL18mm_293kV_cubic

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.94" -field_rod_radius=1.8e-3 -field_amplitude=9.9e5 -cross%write=T -plane%write=T -table_data%input_interpolation='cubic_spline' -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL18mm_297kV_cubic

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.94" -field_rod_radius=1.8e-3 -field_amplitude=9.96667e5 -cross%write=T -plane%write=T -table_data%input_interpolation='cubic_spline' -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL18mm_299kV_cubic


#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.94" -field_rod_radius=1.8e-3 -field_amplitude=9.817e5 -cross%write=T -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL18mm_294.51kV





#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.9133333" -field_rod_radius=2.6e-3 -field_amplitude=9.03667e5 -cross%write=T -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL26mm_271.1kV


#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.9766667" -field_rod_radius=0.7e-3 -field_amplitude=12.50333333e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL7mm_375.1kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.9766667" -field_rod_radius=0.7e-3 -field_amplitude=12.50166667e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL7mm_375.05kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.976667" -field_rod_radius=0.7e-3 -field_amplitude=12.505033333e5 -cross%write=T -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL7mm_375.151kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="240 240" -field_rod_r0="0 0.976667" -field_rod_radius=0.7e-3 -field_amplitude=12.505033333e5 -cross%write=T -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL7mm_375.151kV_r06667_cgs240



#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.984" -field_rod_radius=0.2e-3 -end_streamer_length=100e-3 -field_amplitude=17.584688e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL2mm_219.8086kV_cgs512

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.976" -field_rod_radius=0.3e-3 -end_streamer_length=100e-3 -field_amplitude=15.74936e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL3mm_196.867kV_cgs512

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.968" -field_rod_radius=0.4e-3 -end_streamer_length=100e-3 -field_amplitude=14.5648e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL4mm_182.06kV_cgs512

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.96" -field_rod_radius=0.5e-3 -end_streamer_length=100e-3 -field_amplitude=13.696e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL5mm_171.20kV_cgs512

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.944" -field_rod_radius=0.7e-3 -end_streamer_length=95e-3 -field_amplitude=12.4976e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL7mm_156.22kV_cgs512

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=95e-3 -field_amplitude=11.688e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL9mm_146.1kV_cgs512

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -end_streamer_length=90e-3 -field_amplitude=10.808e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL12mm_135.1kV_cgs512

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.88" -field_rod_radius=1.5e-3 -end_streamer_length=85e-3 -field_amplitude=10.168e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL15mm_127.1kV_cgs512

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.856" -field_rod_radius=1.8e-3 -end_streamer_length=85e-3 -field_amplitude=9.664e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL18mm_120.8kV_cgs512

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=80e-3 -field_amplitude=9.232e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL21mm_115.4kV_cgs512


#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -end_streamer_length=90e-3 -field_amplitude=10.808e5 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL12mm_135.1kV_cgs128

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="200 200" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -end_streamer_length=90e-3 -field_amplitude=10.808e5 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL12mm_135.1kV_cgs200

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -end_streamer_length=90e-3 -field_amplitude=10.808e5 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL12mm_135.1kV_cgs256

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="320 320" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -end_streamer_length=90e-3 -field_amplitude=10.808e5 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL12mm_135.1kV_cgs320

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="400 400" -field_rod_r0="0 0.904" -field_rod_radius=1.2e-3 -end_streamer_length=90e-3 -field_amplitude=10.808e5 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL12mm_135.1kV_cgs400


#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="200 200" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=95e-3 -field_amplitude=11.688e5 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL9mm_146.1kV_cgs200

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="320 320" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=95e-3 -field_amplitude=11.688e5 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL9mm_146.1kV_cgs320

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="400 400" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=95e-3 -field_amplitude=11.688e5 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL9mm_146.1kV_cgs400

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=95e-3 -field_amplitude=11.688e5 -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL9mm_146.1kV_cgs256


#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="64 64" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=80e-3 -field_amplitude=9.232e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL21mm_115.4kV_cgs64

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=80e-3 -field_amplitude=9.232e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL21mm_115.4kV_cgs128

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="200 200" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=80e-3 -field_amplitude=9.232e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL21mm_115.4kV_cgs200

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="256 256" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=80e-3 -field_amplitude=9.232e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL21mm_115.4kV_cgs256

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="320 320" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=80e-3 -field_amplitude=9.232e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL21mm_115.4kV_cgs320

#./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="400 400" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=80e-3 -field_amplitude=9.232e5 -plane%write=T -output%name=/export/scratch2/baohong/afivo-streamer/negative_2d/output/domain_125mm/no_electrode/neg_EL21mm_115.4kV_cgs400


#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="240 240" -field_rod_r0="0 0.96" -field_rod_radius=1.2e-3 -field_amplitude=10.8893333e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL12mm_326.68kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="200 200" -field_rod_r0="0 0.97" -field_rod_radius=0.9e-3 -field_amplitude=11.7216667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL9mm_351.65kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="112 112" -field_rod_r0="0 0.95" -field_rod_radius=1.5e-3 -field_amplitude=10.307e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL15mm_309.21kV


#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="360 360" -field_rod_r0="0 0.96" -field_rod_radius=1.2e-3 -field_amplitude=10.8736667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL12mm_326.21kV


#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="320 320" -field_rod_r0="0 0.97" -field_rod_radius=0.9e-3 -field_amplitude=11.7336667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL9mm_352.01kV


#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="280 280" -field_rod_r0="0 0.97" -field_rod_radius=0.9e-3 -field_amplitude=11.7376667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL9mm_352.13kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="280 280" -field_rod_r0="0 0.976667" -field_rod_radius=0.7e-3 -field_amplitude=12.513e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL7mm_375.39kV


#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.99" -field_rod_radius=0.3e-3 -field_amplitude=15.75129076667e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_steady/neg_EL3mm_472.538723kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.99" -field_rod_radius=0.3e-3 -field_amplitude=15.71795743333e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_EL3-12-25mm_unstable/neg_EL3mm_471.538723kV

#./streamer air_negative_300mm_chem_electro3mm.cfg -coarse_grid_size="512 512" -field_rod_r0="0 0.99" -field_rod_radius=0.3e-3 -field_amplitude=15.7846241e5 -cross%write=T -plane%write=T -output%name+=neg_d300mm_EL3-12-25mm_unstable/neg_EL3mm_473.538723kV

