#!/bin/bash

cd ../


#./streamer d20mm_air.cfg -field_given_by="field -1.6e6" -output%name=/export/scratch3/baohong/eco_gas/air/air_1bar_pos_1.6e6

#./streamer d20mm_air.cfg -field_given_by="field 1.8e6" -output%name=/export/scratch3/baohong/eco_gas/air/air_1bar_neg_1.8e6

./streamer d20mm_air.cfg -field_given_by="field 1.6e6" -background_density=1e13 -output%name=/export/scratch3/baohong/eco_gas/air/air_1bar_neg_1.6e6_bd1e13

./streamer d20mm_air.cfg -field_given_by="field 1.7e6" -background_density=1e13 -output%name=/export/scratch3/baohong/eco_gas/air/air_1bar_neg_1.7e6_bd1e13

./streamer d20mm_air.cfg -field_given_by="field 1.8e6" -background_density=1e13 -output%name=/export/scratch3/baohong/eco_gas/air/air_1bar_neg_1.8e6_bd1e13