#!/bin/bash

cd ../


#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-0.97e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -output%name+=EL3mm_0.97e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.0e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -output%name+=EL3mm_1.0e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.2e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -output%name+=EL3mm_1.2e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.5e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -output%name+=EL3mm_1.5e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.8e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -output%name+=EL3mm_1.8e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -output%name+=EL3mm_2.2e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.6e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -output%name+=EL3mm_2.6e6



#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-0.97e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL3mm_0.97e6_im

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.0e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL3mm_1.0e6_im

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.2e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL3mm_1.2e6_im

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.5e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL3mm_1.5e6_im

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.8e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL3mm_1.8e6_im

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL3mm_2.2e6_im

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.6e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL3mm_2.6e6_im



#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.5e6 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.5e-2 -output%name+=EL4mm_1.5e6_conductivity



#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.45e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -end_time=5e-7 -output%name+=EL1mm_1.45e6_new

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.5e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -end_time=5e-7 -output%name+=EL1mm_1.5e6_new

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.6e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -end_time=5e-7 -output%name+=EL1mm_1.6e6_new


#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.3e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -end_time=5e-7 -output%name+=EL1mm_2.3e6_new

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.4e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -end_time=5e-7 -output%name+=EL1mm_2.4e6_new

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.5e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -end_time=5e-7 -output%name+=EL1mm_2.5e6_new

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.6e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -end_time=5e-7 -output%name+=EL1mm_2.6e6_new



#./streamer air_d20mm_chemistry_conductivity.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-0.9e6 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.5e-2 -output%name+=EL4mm_0.9e6_qua_cdty

#./streamer air_d20mm_chemistry_conductivity.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.5e6 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.5e-2 -output%name+=EL4mm_1.5e6_qua_cdty



#./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.0e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -dt_min=1e-16 -output%name+=EL3mm_1.0e6

#./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.1e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=EL3mm_1.1e6

#./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.2e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=EL3mm_1.2e6

#./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.3e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=EL3mm_1.3e6

#./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.4e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=EL3mm_1.4e6

#./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.5e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=EL3mm_1.5e6

#./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.8e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=EL3mm_1.8e6

#./streamer air_d20mm_chemistry.cfg -field_amplitude=-2.2e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=EL3mm_2.2e6

#./streamer air_d20mm_chemistry.cfg -field_amplitude=-2.6e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=EL3mm_2.6e6



#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.0e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -dt_min=1e-16 -output%name+=dp_EL3mm_1.0e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.1e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=dp_EL3mm_1.1e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.2e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=dp_EL3mm_1.2e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.3e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=dp_EL3mm_1.3e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.4e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=dp_EL3mm_1.4e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.5e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=dp_EL3mm_1.5e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.8e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=dp_EL3mm_1.8e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=dp_EL3mm_2.2e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.6e6 -field_rod_r0="0 0.865" -field_rod_radius=0.3e-3 -end_streamer_length=1.5e-2 -output%name+=dp_EL3mm_2.6e6


./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.45e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -table_data%xspacing='linear' -end_streamer_length=1.7e-2 -dt_min=1e-16 -output%name+=EL1mm_1.45e6

./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.5e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -table_data%xspacing='linear' -end_streamer_length=1.7e-2 -dt_min=1e-16 -output%name+=EL1mm_1.5e6

