#!/bin/bash

cd ../


#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.45e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -output%name+=EL1mm_1.45e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.5e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -output%name+=EL1mm_1.5e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.8e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -output%name+=EL1mm_1.8e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -output%name+=EL1mm_2.2e6

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.6e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -output%name+=EL1mm_2.6e6



#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.45e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL1mm_1.45e6_im

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.5e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL1mm_1.5e6_im

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.8e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL1mm_1.8e6_im

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL1mm_2.2e6_im

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.6e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -input_data%ion_mobilities="2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4 -2.2e-4" -input_data%mobile_ions="N_plus N2_plus N3_plus N4_plus O_plus O2_plus O3_plus O4_plus NO_plus N2O2_plus O_min O2_min O3_min O4_min" -output%name+=EL1mm_2.6e6_im




#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-0.9e6 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.5e-2 -output%name+=EL4mm_0.9e6_conductivity



#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Baohong_reactions_Phelps_0.05td.txt -table_data%input_interpolation='linear'  -table_data%size=20000 -output%name+=EL2mm_2.2e6_0.05td_size20000

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Baohong_reactions_Phelps_0.05td.txt -table_data%input_interpolation='linear'  -table_data%size=10000 -output%name+=EL2mm_2.2e6_0.05td_size10000

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Baohong_reactions_Phelps_0.05td.txt -table_data%input_interpolation='linear'  -table_data%size=1000 -output%name+=EL2mm_2.2e6_0.05td_size1000


#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Baohong_reactions_Phelps.txt -table_data%input_interpolation='linear'  -table_data%size=1000 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/EL2mm_2.2e6_0.01td_size1000

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Baohong_reactions_Phelps.txt -table_data%input_interpolation='linear'  -table_data%size=100000 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/EL2mm_2.2e6_0.01td_size100000

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Baohong_reactions_Phelps.txt -table_data%input_interpolation='linear'  -table_data%size=20000 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/EL2mm_2.2e6_0.01td_size20000

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Baohong_reactions_Phelps.txt -table_data%input_interpolation='linear'  -table_data%size=50000 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/EL2mm_2.2e6_0.01td_size50000


#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Baohong_reactions_Phelps_0.1td.txt -table_data%input_interpolation='linear'  -table_data%size=1000 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/EL2mm_2.2e6_0.1td_size1000



#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -table_data%xspacing='quadratic' -table_data%size=1000 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/EL2mm_2.2e6_quadratic_size1000



#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.4e6 -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -end_time=5e-7 -table_data%xspacing='linear' -table_data%size=20000 -output%name+=EL2mm_2.4e6_new

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.5e6 -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -end_time=5e-7 -table_data%xspacing='linear' -table_data%size=20000 -output%name=/export/scratch2/md/baohong/chemistry/two_pulse_new/EL2mm_2.5e6_new


#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.6e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -end_time=5e-7 -table_data%xspacing='linear' -table_data%size=20000 -output%name=/export/scratch2/md/baohong/chemistry/two_pulse_new/EL1mm_2.6e6_new

#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.7e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -end_time=5e-7 -table_data%xspacing='linear' -table_data%size=20000 -output%name=/export/scratch2/md/baohong/chemistry/two_pulse_new/EL1mm_2.7e6_new


#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.5e6 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.5e-2 -end_time=1e-6 -output%dt=1e-9 -output%name+=EL4mm_1.5e6_1us


#./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.5e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -output%name=/export/scratch2/baohong/chemistry/test/EL1mm_1.5e6


#./streamer air_d20mm_chemistry.cfg -field_amplitude=-0.78e6 -field_rod_r0="0 0.73" -field_rod_radius=0.6e-3 -end_streamer_length=1.2e-2 -output%name=/export/scratch2/baohong/chemistry/test/EL6mm_0.78e6



./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-0.9e6 -field_waveform%turn_off_z=10e-3 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.4e-2 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/dp_EL4mm_0.9e6_z10e-3

./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.0e6 -field_waveform%turn_off_z=10e-3 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.4e-2 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/dp_EL4mm_1.0e6_z10e-3

./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.1e6 -field_waveform%turn_off_z=10e-3 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.4e-2 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/dp_EL4mm_1.1e6_z10e-3

./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.2e6 -field_waveform%turn_off_z=10e-3 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.4e-2 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/dp_EL4mm_1.2e6_z10e-3

./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.3e6 -field_waveform%turn_off_z=10e-3 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.4e-2 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/dp_EL4mm_1.3e6_z10e-3

./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.4e6 -field_waveform%turn_off_z=10e-3 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.4e-2 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/dp_EL4mm_1.4e6_z10e-3

./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.5e6 -field_waveform%turn_off_z=10e-3 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.4e-2 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/dp_EL4mm_1.5e6_z10e-3

./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-1.8e6 -field_waveform%turn_off_z=10e-3 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.4e-2 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/dp_EL4mm_1.8e6_z10e-3

./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.2e6 -field_waveform%turn_off_z=10e-3 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.4e-2 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/dp_EL4mm_2.2e6_z10e-3

./streamer air_d20mm_chemistry.cfg -field_waveform%enabled=T -field_waveform%pulse_field=-2.6e6 -field_waveform%turn_off_z=10e-3 -field_rod_r0="0 0.82" -field_rod_radius=0.4e-3 -end_streamer_length=1.4e-2 -output%name=/export/scratch3/baohong/chemistry/two_pulse_new/dp_EL4mm_2.6e6_z10e-3
