#!/bin/bash

cd ../

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.15e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -dt_min=1e-17 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_1.15e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.2e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_1.2e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.3e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_1.3e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.4e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_1.4e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.5e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_1.5e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.6e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_1.6e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.7e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_1.7e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.8e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_1.8e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.9e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_1.9e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-2.0e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_2.0e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-2.2e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_2.2e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-2.4e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch2/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_2.4e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-2.6e6 -field_waveform%turn_off_z=24e-3 -field_rod_r0="0 0.955" -field_rod_radius=0.2e-3 -end_streamer_length=3.7e-2 -output%name=/export/scratch3/baohong/chemistry/d40mm_double_pulses/EL2mm_SL14mm_2.6e6


