#!/bin/bash

cd ../

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.0e6 -field_waveform%fall_time=0.5e-9 -field_waveform%turn_off_z=18e-3 -field_rod_r0="0 0.91" -field_rod_radius=0.4e-3 -end_streamer_length=3.5e-2 -compute_power_density=T -output%write_derivatives="e N2_star_J O2_star_J N2_star_v1 O2_star_v1 O2_star_a N__hat4S O__hat3P NO N2O" -output%name=/export/scratch2/md/baohong/chemistry/d40mm_double_pulses/EL4mm_SL18mm_1.0e6_new

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.4e6 -field_waveform%fall_time=0.5e-9 -field_waveform%turn_off_z=18e-3 -field_rod_r0="0 0.91" -field_rod_radius=0.4e-3 -end_streamer_length=3.5e-2 -compute_power_density=T -output%write_derivatives="e N2_star_J O2_star_J N2_star_v1 O2_star_v1 O2_star_a N__hat4S O__hat3P NO N2O" -output%name=/export/scratch2/md/baohong/chemistry/d40mm_double_pulses/EL4mm_SL18mm_1.4e6_new

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-1.8e6 -field_waveform%fall_time=0.5e-9 -field_waveform%turn_off_z=18e-3 -field_rod_r0="0 0.91" -field_rod_radius=0.4e-3 -end_streamer_length=3.5e-2 -compute_power_density=T -output%write_derivatives="e N2_star_J O2_star_J N2_star_v1 O2_star_v1 O2_star_a N__hat4S O__hat3P NO N2O" -output%name=/export/scratch2/md/baohong/chemistry/d40mm_double_pulses/EL4mm_SL18mm_1.8e6_new

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-2.2e6 -field_waveform%fall_time=0.5e-9 -field_waveform%turn_off_z=18e-3 -field_rod_r0="0 0.91" -field_rod_radius=0.4e-3 -end_streamer_length=3.5e-2 -compute_power_density=T -output%write_derivatives="e N2_star_J O2_star_J N2_star_v1 O2_star_v1 O2_star_a N__hat4S O__hat3P NO N2O" -output%name=/export/scratch2/md/baohong/chemistry/d40mm_double_pulses/EL4mm_SL18mm_2.2e6_new

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-2.6e6 -field_waveform%fall_time=0.5e-9 -field_waveform%turn_off_z=18e-3 -field_rod_r0="0 0.91" -field_rod_radius=0.4e-3 -end_streamer_length=3.5e-2 -compute_power_density=T -output%write_derivatives="e N2_star_J O2_star_J N2_star_v1 O2_star_v1 O2_star_a N__hat4S O__hat3P NO N2O" -output%name=/export/scratch2/md/baohong/chemistry/d40mm_double_pulses/EL4mm_SL18mm_2.6e6_new