#!/bin/bash

cd ../

# air, background density=1e11, electrode length=21e-3, electode radius=2.1e-3, output%dt=5e-10, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_1000points.txt




./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=90e-3 -end_time=200e-9 -field_amplitude=0.66251304e6 -cross%write=T -output%name+=negative_electro21mm_decay/neg_EL21mm_ER2.1mm_0.8127e6

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=90e-3 -end_time=200e-9 -field_amplitude=0.73229416e6 -cross%write=T -output%name+=negative_electro21mm_decay/neg_EL21mm_ER2.1mm_0.8983e6

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=90e-3 -end_time=200e-9 -field_amplitude=0.78242896e6 -cross%write=T -output%name+=negative_electro21mm_decay/neg_EL21mm_ER2.1mm_0.9598e6

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=90e-3 -end_time=200e-9 -field_amplitude=0.8103088e6 -cross%write=T -output%name+=negative_electro21mm_decay/neg_EL21mm_ER2.1mm_0.9940e6

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=90e-3 -end_time=200e-9 -field_amplitude=0.82913992e6 -cross%write=T -output%name+=negative_electro21mm_decay/neg_EL21mm_ER2.1mm_1.0171e6

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=90e-3 -end_time=200e-9 -field_amplitude=0.84430264e6 -cross%write=T -output%name+=negative_electro21mm_decay/neg_EL21mm_ER2.1mm_1.0357e6

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=90e-3 -end_time=200e-9 -field_amplitude=0.85734584e6 -cross%write=T -output%name+=negative_electro21mm_decay/neg_EL21mm_ER2.1mm_1.0517e6

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=90e-3 -end_time=200e-9 -field_amplitude=0.87601392e6 -cross%write=T -output%name+=negative_electro21mm_decay/neg_EL21mm_ER2.1mm_1.0746e6

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=90e-3 -end_time=200e-9 -field_amplitude=0.89729064e6 -cross%write=T -output%name+=negative_electro21mm_decay/neg_EL21mm_ER2.1mm_1.1007e6

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=90e-3 -end_time=200e-9 -field_amplitude=0.92305096e6 -cross%write=T -output%name+=negative_electro21mm_decay/neg_EL21mm_ER2.1mm_1.1323e6

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="32 32" -field_rod_r0="0 0.832" -field_rod_radius=2.1e-3 -end_streamer_length=90e-3 -end_time=200e-9 -field_amplitude=0.94815912e6 -cross%write=T -output%name+=negative_electro21mm_decay/neg_EL21mm_ER2.1mm_1.1631e6




