#!/bin/bash

cd ../

# air, background density=1e11, electrode length=9e-3, electode radius=0.9e-3, output%dt=5e-10, refine_min_dx=1e-6, refine_adx=0.8, refine_adx_fac=1.25, air_phelps_chemistry_small_v0_full.txt (add positive ion conversion and electron recombination and recombination)



./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=0.98230944e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.0668e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.05210608e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.1426e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.08783312e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.1814e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.11536504e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.2113e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.12972952e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.2269e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.13939792e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.2374e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.14676432e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.2454e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.15201288e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.2511e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.15615648e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.2556e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.16195752e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.2619e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.16904768e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.2696e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.17834776e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.2797e6_full

./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.28912e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.4e6_full

# stable_streamer
./streamer air_negative_125mm_chem_electro9mm.cfg -coarse_grid_size="128 128" -field_rod_r0="0 0.928" -field_rod_radius=0.9e-3 -end_streamer_length=100e-3 -end_time=200e-9 -field_amplitude=1.17383584e6 -cross%write=T -input_data%file=../../transport_data/air_phelps_chemistry_small_v0_full.txt -output%name+=negative_electro9mm_decay_full/neg_EL9mm_ER0.9mm_1.2748e6_full
