#!/bin/bash

cd ../


./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.45e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -output%name+=EL1mm_1.45e6

./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.5e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -output%name+=EL1mm_1.5e6

./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.8e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -output%name+=EL1mm_1.8e6

./streamer air_d20mm_chemistry.cfg -field_amplitude=-2.2e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -output%name+=EL1mm_2.2e6

./streamer air_d20mm_chemistry.cfg -field_amplitude=-2.6e6 -field_rod_r0="0 0.955" -field_rod_radius=0.1e-3 -output%name+=EL1mm_2.6e6





