#!/bin/bash

cd ../


./streamer pos_d100mm_chemistry.cfg -field_amplitude=2.0e6 -field_rise_time=30e-9 -output%name+=test/neg_EL6mm_2.0e6_30ns

./streamer pos_d100mm_chemistry.cfg -field_amplitude=2.0e6 -field_rise_time=40e-9 -output%name+=test/neg_EL6mm_2.0e6_40ns

./streamer pos_d100mm_chemistry.cfg -field_amplitude=2.0e6 -field_rise_time=50e-9 -output%name+=test/neg_EL6mm_2.0e6_50ns