#!/bin/bash

cd ../


./streamer air_d50mm_chemistry.cfg -field_amplitude=-2.0e6  -field_rod_r0="0 0.982" -field_rod_radius=0.1e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Baohong_reactions_Itikawa.txt -output%name=/export/scratch2/md/baohong/chemistry/Baohong_reactions/EL1mm_2.0e6_Itikawa

./streamer air_d50mm_chemistry.cfg -field_amplitude=-2.0e6  -field_rod_r0="0 0.982" -field_rod_radius=0.1e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Baohong_reactions_Itikawa_1.txt -output%name=/export/scratch2/md/baohong/chemistry/Baohong_reactions/EL1mm_2.0e6_Itikawa_1


./streamer air_d50mm_chemistry.cfg -field_amplitude=-1.6e6  -field_rod_r0="0 0.982" -field_rod_radius=0.1e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Komuro_reactions.txt -output%name=/export/scratch2/md/baohong/chemistry/Baohong_reactions/EL1mm_1.6e6_Korumo

./streamer air_d50mm_chemistry.cfg -field_amplitude=-1.6e6  -field_rod_r0="0 0.982" -field_rod_radius=0.1e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_v3.txt -output%name=/export/scratch2/md/baohong/chemistry/Baohong_reactions/EL1mm_1.6e6_v3

./streamer air_d50mm_chemistry.cfg -field_amplitude=-1.6e6  -field_rod_r0="0 0.982" -field_rod_radius=0.1e-3 -input_data%file=../../transport_data/N2_O2/air_chemistry_Baohong_reactions.txt -output%name=/export/scratch2/md/baohong/chemistry/Baohong_reactions/EL1mm_1.6e6_Phelps

./streamer air_d50mm_chemistry.cfg -field_amplitude=-1.6e6  -field_rod_r0="0 0.982" -field_rod_radius=0.1e-3 -input_data%file=../../transport_data/Air_Kawa_Itikawa_Kossyi.txt -output%name=/export/scratch2/md/baohong/chemistry/Baohong_reactions/EL1mm_1.6e6_Andy

