#!/bin/bash

cd ../


#./streamer air_d50mm_chemistry.cfg -field_amplitude=-1.6e6  -field_rod_r0="0 0.982" -field_rod_radius=0.1e-3 -output%name+=EL1mm_1.6e6

#./streamer air_d50mm_chemistry.cfg -field_amplitude=-1.6e6  -field_rod_r0="0 0.964" -field_rod_radius=0.2e-3 -output%name+=EL2mm_1.6e6

#./streamer air_d50mm_chemistry.cfg -field_amplitude=-1.6e6  -field_rod_r0="0 0.946" -field_rod_radius=0.3e-3 -output%name+=EL3mm_1.6e6

#./streamer air_d50mm_chemistry.cfg -field_amplitude=-1.6e6  -field_rod_r0="0 0.928" -field_rod_radius=0.4e-3 -output%name+=EL4mm_1.6e6

#./streamer air_d50mm_chemistry.cfg -field_amplitude=-1.6e6  -field_rod_r0="0 0.91" -field_rod_radius=0.5e-3 -output%name+=EL5mm_1.6e6


#./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.2e6  -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -output%name+=d20mm_EL2mm_1.2e6

./streamer air_d20mm_chemistry.cfg -field_amplitude=-1.15e6  -field_rod_r0="0 0.91" -field_rod_radius=0.2e-3 -output%name+=d20mm_EL2mm_1.15e6




