#!/bin/bash

cd ../


#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=5e-9 -output%name+=test/pos_EL6mm_2.0e6_5ns

#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=10e-9 -output%name+=test/pos_EL6mm_2.0e6_10ns

#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=50e-9 -output%name+=test/pos_EL6mm_2.0e6_50ns



#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -output%name+=test/seed_pos_EL6mm_2.0e6

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=5e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_5ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=10e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_10ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=50e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_50ns



#./streamer pos_d100mm_chemistry_cone_seed.cfg -field_amplitude=-2.0e6 -output%name+=test/cone_seed_pos_EL6mm_2.0e6

#./streamer pos_d100mm_chemistry_cone_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=50e-9 -output%name+=test/cone_seed_pos_EL6mm_2.0e6_50ns



#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -seed_falloff="gaussian" -output%name+=test/seed_pos_EL6mm_2.0e6_gau



#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -seed_rel_r0="0 0.94"  -seed_rel_r1="0 0.94" -output%name+=test/seed_pos_EL6mm_2.0e6_z0.94



#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -seed_density=1e15 -output%name+=test/seed_pos_EL6mm_2.0e6_sd1e15



#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -seed_density=1e17 -output%name+=test/seed_pos_EL6mm_2.0e6_sd1e17



#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -refine_adx=0.5 -output%name+=test/seed_pos_EL6mm_2.0e6_adx0.5



#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -refine_adx_fac=1.25 -output%name+=test/seed_pos_EL6mm_2.0e6_fac1.25



#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-1.0e6 -gas%pressure=0.5 -seed_density=1.25e19 -output%name+=test/seed_pos_EL6mm_1.0e6_scale_0.5bar

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-1.0e6 -gas%pressure=0.5 -seed_density=1.25e19 -field_rise_time=50e-9 -output%name+=test/seed_pos_EL6mm_1.0e6_scale_0.5bar_50ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-4.0e5 -gas%pressure=0.2 -seed_density=2e18 -output%name+=test/seed_pos_EL6mm_4.0e5_scale_0.2bar

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-4.0e5 -gas%pressure=0.2 -seed_density=2e18 -field_rise_time=50e-9 -output%name+=test/seed_pos_EL6mm_4.0e5_scale_0.2bar_50ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e5 -gas%pressure=0.1 -seed_density=5e17 -output%name+=test/seed_pos_EL6mm_2.0e5_scale_0.1bar

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e5 -gas%pressure=0.1 -seed_density=5e17 -field_rise_time=50e-9 -end_time=2.5e-7 -output%name+=test/seed_pos_EL6mm_2.0e5_scale_0.1bar_50ns

