#!/bin/bash

cd ../


#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=1e-9 -output%name+=test/pos_EL6mm_2.0e6_1ns

#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=2e-9 -output%name+=test/pos_EL6mm_2.0e6_2ns

#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=3e-9 -output%name+=test/pos_EL6mm_2.0e6_3ns

#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=4e-9 -output%name+=test/pos_EL6mm_2.0e6_4ns

#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=5e-9 -output%name+=test/pos_EL6mm_2.0e6_5ns

#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=10e-9 -output%name+=test/pos_EL6mm_2.0e6_10ns

#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=20e-9 -output%name+=test/pos_EL6mm_2.0e6_20ns

#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=30e-9 -output%name+=test/pos_EL6mm_2.0e6_30ns

#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=40e-9 -output%name+=test/pos_EL6mm_2.0e6_40ns

#./streamer pos_d100mm_chemistry.cfg -field_amplitude=-2.0e6 -field_rise_time=50e-9 -output%name+=test/pos_EL6mm_2.0e6_50ns



#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -output%name+=test/seed_pos_EL6mm_2.0e6

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=1e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_1ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=2e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_2ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=3e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_3ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=4e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_4ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=5e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_5ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=10e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_10ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=20e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_20ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=30e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_30ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=40e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_40ns

#./streamer pos_d100mm_chemistry_seed.cfg -field_amplitude=-2.0e6 -field_rise_time=50e-9 -output%name+=test/seed_pos_EL6mm_2.0e6_50ns


