#!/bin/bash

cd ../

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-2.4e6 -field_waveform%turn_off_z=11e-3 -field_rod_r0="0 0.91" -field_rod_radius=0.4e-3 -end_streamer_length=3.5e-2 -output%name=/export/scratch2/md/baohong/chemistry/d40mm_double_pulses/EL4mm_SL25mm_2.4e6

./streamer air_d40mm_chemistry.cfg -field_waveform%pulse_field=-2.6e6 -field_waveform%turn_off_z=11e-3 -field_rod_r0="0 0.91" -field_rod_radius=0.4e-3 -end_streamer_length=3.5e-2 -output%name=/export/scratch2/md/baohong/chemistry/d40mm_double_pulses/EL4mm_SL25mm_2.6e6

