#!/usr/bin/env python

# Author: Jannis Teunissen

# Description: Convert Bolsig+ output (one big table) to a list of energy,
# mobility, diffusion constant, ionization coefficient and attachment
# coefficient

# TODO: Could write this more compactly, but for now works okay.

import argparse
import re
import numpy as np


def getArgs():
    "Set the arguments, read them in, and return them"
    parser = argparse.ArgumentParser(description="Converter for Bolsig+ data")
    parser.add_argument("infile", type=str, help="input file")
    parser.add_argument("outfile", type=str, help="output file")
    parser.add_argument("-T", type=float, default=300.,
                        help="Gas temperature (K)")
    parser.add_argument("-p", type=float,
                        default=1.0, help="Gas pressure (bar)")

    return parser.parse_args()


def convert():
    cfg = getArgs()

    with open(cfg.infile, 'r') as f:
        fr = f.read()
        fr = re.sub(r'(\r\n|\r|\n)', '\n', fr)  # Fix newlines

    # Look up columns of things we are interested in
    Efield_label = 'E/N(Td)'
    match = re.search(r'(A\S*).*Mean energy \(eV\)', fr)
    eV_label = match.group(1)
    match = re.search(r'(A\S*).*Mobility \*N \(1\/m\/V\/s\)', fr)
    mu_label = match.group(1)
    match = re.search(r'(A\S*).*Diffusion coefficient'
                      + r' \*N \(1\/m\/s\)', fr)
    dc_label = match.group(1)
    match = re.search(r'(A\S*).*Townsend ioniz. coef. alpha/N \(m2\)', fr)
    alpha_label = match.group(1)
    eta_label = 'I_DO_NOT_EXIST?'

    # Listing of columns at the start (e.g. R# E/N (Td) A1 A2 A6 ...)
    match = re.search(r'.*(\s+(A\d+)){5,}.*', fr)
    # Remove the space from 'E/N (Td)'
    header = re.sub(r'E/N \(', r'E/N(', match.group(0))
    # The table starts after the header
    tbl_start = match.end() + 1

    # Find indexes of columns
    column_order = header.split()
    Efield_col = column_order.index(Efield_label)
    eV_col = column_order.index(eV_label)
    mu_col = column_order.index(mu_label)
    dc_col = column_order.index(dc_label)
    alpha_col = column_order.index(alpha_label)
    if eta_label in column_order:
        eta_col = column_order.index(eta_label)
    else:
        eta_col = -1

    # Find end of table
    # Double Newline at the end
    match = re.search(r'^\s*$', fr[tbl_start:], re.M)
    tbl_end = tbl_start + match.start() - 1

    tbl_string = fr[tbl_start:tbl_end].splitlines()
    tbl_data = np.genfromtxt(tbl_string)

    # Check if all data was read correctly
    if np.any(np.isnan(tbl_data)):
        print("! Warning: some data could not be read properly!")
        print("! Number of missing values: {}".format(
            np.sum(np.isnan(tbl_data))))

    boltzmann_const = 1.3806488e-23
    gas_num_dens = cfg.p * 1e5 / (boltzmann_const * cfg.T)

    print("Gas temperature %.3e Kelvin" % (cfg.T))
    print("Gas pressure     %.3e bar" % (cfg.p))
    print("Gas #density     %.3e /m3" % (gas_num_dens))

    # Clear file
    with open(cfg.outfile, 'w') as f:
        f.close()

    with open(cfg.outfile, 'ab') as f:
        tbl_data[:, Efield_col] = (tbl_data[:, Efield_col] *
                                   1e-21 * gas_num_dens)
        tbl_data[:, mu_col] = tbl_data[:, mu_col] / gas_num_dens
        tbl_data[:, dc_col] = tbl_data[:, dc_col] / gas_num_dens
        tbl_data[:, alpha_col] = tbl_data[:, alpha_col] * gas_num_dens

        write_entry(r'efield[V/m]_vs_mu[m2/Vs]', tbl_data[:, Efield_col],
                    tbl_data[:, mu_col], f)
        write_entry(r'efield[V/m]_vs_dif[m2/s]', tbl_data[:, Efield_col],
                    tbl_data[:, dc_col], f)
        write_entry(r'efield[V/m]_vs_alpha[1/m]', tbl_data[:, Efield_col],
                    tbl_data[:, alpha_col], f)
        if (eta_col != -1):
            tbl_data[:, eta_col] = tbl_data[:, eta_col] * gas_num_dens
            write_entry(r'efield[V/m]_vs_eta[1/m]',
                        tbl_data[:, Efield_col], tbl_data[:, eta_col], f)
            write_entry(r'efield[V/m]_vs_energy[eV]',
                        tbl_data[:, Efield_col], tbl_data[:, eV_col], f)


def write_entry(entry_name, x_data, y_data, f):
    out_data = np.column_stack([x_data, y_data])
    hdr = ('\n\n' + entry_name + '\n' +
           'COMMENT: generated by bolsig_convert.py' +
           '\n-----------------------\n')
    ftr = '-----------------------\n'
    f.write(hdr.encode('ascii'))
    np.savetxt(f, out_data)
    f.write(ftr.encode('ascii'))


if __name__ == '__main__':
    convert()
