name: 'afivo-streamer regression tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install gfortran
          sudo apt install python3-numpy

      - name: Compile
        run: make

      - name: Run tests
        run: ./run_test.sh

